# -*- coding: utf-8 -*-
"""TOPIC 1 ANALYSES

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bdh-Q6kvKsAc8ljmNIlUMsRDT_-PvPoW
"""

#PHASE 1: PHASE 1: DNA METHYLATION DATA PIPELINE

# Step 1.1 – Mount Google Drive
## To access input data files and store results persistently,
## we first mount your Google Drive within the Colab environment.
## This ensures all .bed.gz, .rds, .csv, and image outputs are
## directly linked to your existing Drive structure.
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# Step 1.2 – Install Required Python Libraries and Enable R Support
## This step installs core Python libraries required for methylation analysis,
## including GEOparse for data handling, pandas/numpy for matrix operations,
## seaborn/matplotlib for plotting, and SHAP for model interpretability.
## We also install `rpy2` to enable native R code execution within Colab notebooks.
!pip install --quiet rpy2==3.5.15 GEOparse pandas numpy scipy seaborn matplotlib \
                     statsmodels scikit-learn shap

## Load the rpy2 IPython extension, which allows R code blocks to run inside Colab.
# %load_ext rpy2.ipython

# Step 1.3 – Install Conda and Mamba via condacolab
## We use condacolab to install and configure Conda inside the Colab environment.
## This allows us to install Bioconductor and R-specific packages cleanly, such as methylKit and ChIPseeker.
## Note: This cell will trigger a Colab runtime restart after installation is complete.
!pip install --quiet condacolab
import condacolab
condacolab.install()

# Commented out IPython magic to ensure Python compatibility.
# # Step 1.4 – Install Required R and Bioconductor Packages
# ## This step installs all core R packages used throughout Phases 1 and 2.
# ## These include: methylKit for methylation data processing,
# ## ggplot2 and ggrepel for publication-quality plots,
# ## data.table for fast data manipulation,
# ## GenomicRanges and IRanges for handling genomic regions,
# ## ChIPseeker and TxDb for CpG annotation,
# ## and BiocManager to facilitate Bioconductor package installation.
# 
# %%R
# # Install BiocManager if not already present
# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager", repos = "http://cran.us.r-project.org")
# 
# # Core methylation and genomics packages
# BiocManager::install(c("methylKit", "GenomicRanges", "IRanges", "AnnotationDbi",
#                        "TxDb.Hsapiens.UCSC.hg19.knownGene", "ChIPseeker", "org.Hs.eg.db"))
# 
# # Data handling and visualization
# install.packages("data.table", repos = "http://cran.us.r-project.org")
# install.packages("ggplot2", repos = "http://cran.us.r-project.org")
# install.packages("ggrepel", repos = "http://cran.us.r-project.org")
# install.packages("ggridges", repos = "http://cran.us.r-project.org")
# install.packages("viridis", repos = "http://cran.us.r-project.org")
#

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # Step 2.1 – Extract .bed.gz Files from TAR Archive
# ## This step extracts all methylation BED files from the original GEO-supplied archive (GSE54983_RAW.tar).
# ## We specify the output directory inside your Google Drive, ensuring persistent access across sessions.
# ## After extraction, we preview the first five filenames to confirm successful decompression.
# 
# raw_tar="/content/drive/MyDrive/GSE54983_RAW.tar"
# out_dir="/content/drive/MyDrive/GSE54983_RAW"
# 
# mkdir -p "$out_dir"
# tar -xf "$raw_tar" -C "$out_dir"
# 
# echo "Extraction finished. First five files:"
# ls -1 "$out_dir" | head -n 5
#

# Step 2.2 – Create Sample Sheet from Extracted BED Files
## After extracting all BED files, we now construct a sample sheet that maps each file to a unique Sample ID.
## The Sample ID is parsed from the filename prefix (before the first underscore).
## The resulting CSV serves as a reference for downstream methylation loading using methylKit in R.

import pathlib, pandas as pd

bed_dir = pathlib.Path("/content/drive/MyDrive/GSE54983_RAW")
bed_files = sorted(bed_dir.glob("*.bed.gz"))

samples = pd.DataFrame({
    "Sample_ID": [f.stem.split("_")[0] for f in bed_files],
    "BED_path": [str(f) for f in bed_files]
})

samples.to_csv("/content/drive/MyDrive/GSE54983_sample_sheet.csv", index=False)
print(f"Sample-sheet written with {len(samples)} entries.")
samples.head()

# Step 2.3 – Preview Structure of a BED File
## Before loading the methylation data into methylKit, we inspect the format of a representative BED file.
## This confirms that the fields (chromosome, start, end, strand, coverage, etc.) are in the correct layout.
## We display the first 5 lines from one of the .bed.gz files in the extracted directory.

import gzip, itertools, pathlib

example_file = pathlib.Path("/content/drive/MyDrive/GSE54983_RAW").glob("*.bed.gz").__next__()
print("Previewing:", example_file)

with gzip.open(example_file, "rt") as fh:
    for line in itertools.islice(fh, 5):
        print(line.strip())

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Step 3.0 – Load Sample Sheet in R
# ## This step imports the sample sheet generated earlier into R.
# ## The sample sheet provides file paths and sample IDs necessary to load methylation data
# ## into a methylRawList object using methylKit in the next step.
# 
# library(data.table)   # fast and memory-efficient CSV reading
# samples <- fread("/content/drive/MyDrive/GSE54983_sample_sheet.csv")
# print(head(samples, 4))
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Step 3.1 – Read BED Files into methylRawList Using Custom Helper
# ## This function safely reads each BED file and parses the methylated/unmethylated counts manually.
# ## We split the 'meth_unmeth' column (e.g., "5/10") into numeric methylated and unmethylated counts,
# ## then use `methods::new()` to build a methylRaw object for each sample.
# ## Finally, we wrap all methylRaw objects into a methylRawList.
# ## This version of the methylRaw constructor sanitizes strand values at load time
# ## and replaces invalid entries (like "b") with "*".
# 
# library(data.table)
# library(methylKit)
# library(methods)
# 
# read_as_methylRaw <- function(fp, sid) {
#   dt <- fread(fp, header = FALSE,
#               col.names = c("chr", "start", "end", "meth_unmeth", "score", "strand"))
# 
#   # Fix strand: replace any value not + or - with "*"
#   dt$strand[!dt$strand %in% c("+", "-")] <- "*"
# 
#   # Parse meth_unmeth into counts
#   parts <- tstrsplit(gsub("'", "", dt$meth_unmeth), "/", fixed = TRUE)
#   dt[, numCs := as.integer(parts[[1]])]
#   dt[, numTs := as.integer(parts[[2]])]
#   dt[, coverage := numCs + numTs]
# 
#   dt2 <- dt[, .(chr, start, end, strand, coverage, numCs, numTs)]
# 
#   new("methylRaw",
#       dt2,
#       sample.id  = sid,
#       assembly   = "hg19",
#       context    = "CpG",
#       resolution = "base")
# }
# 
# # Load sample sheet again
# samples <- fread("/content/drive/MyDrive/GSE54983_sample_sheet.csv")
# samples$group <- c(rep(1, 24), rep(0, 24))
# 
# # Rebuild methylRawList with clean strands
# raw_list <- list()
# for (i in seq_len(nrow(samples))) {
#   raw_list[[i]] <- read_as_methylRaw(samples$BED_path[i], samples$Sample_ID[i])
# }
# meth_list <- new("methylRawList", raw_list, treatment = samples$group)
# 
# # Save corrected version
# saveRDS(meth_list, "/content/drive/MyDrive/meth_list.rds")
# 
# # Preview
# meth_list[[1]][1:5, ]
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Step 4.0 – Filter and Unite CpGs Across Samples (Finalized)
# ## This step filters CpG sites by read coverage to improve reliability.
# ## Specifically, we retain CpGs with a minimum coverage of 10 reads and remove sites in the top 0.1% of coverage.
# ## After filtering, we unite all samples to create a clean methylBase object for downstream analysis.
# 
# library(methylKit)
# 
# # Reload the original methylRawList if needed
# meth_list <- readRDS("/content/drive/MyDrive/meth_list.rds")
# 
# # Filter CpGs: keep those with ≥10 reads and below 99.9th percentile coverage
# meth_filtered <- filterByCoverage(meth_list, lo.count = 10, hi.perc = 99.9)
# 
# # Unite across all samples
# meth_united <- unite(meth_filtered, destrand = FALSE)
# 
# # Save the clean methylBase object
# saveRDS(meth_united, "/content/drive/MyDrive/meth_united.rds")
# 
# # Confirm structure
# cat("Filtered and united methylation matrix dimensions:\n")
# print(dim(meth_united))
# cat("Unique strand values:\n")
# print(unique(meth_united$strand))
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Step 5.0 – Differential Methylation Analysis at CpG-Level
# ## This step performs differential methylation testing between famine-exposed and control groups using logistic regression.
# ## The model accounts for group-wise methylation differences and corrects for multiple comparisons using q-values (FDR).
# ## We then filter to retain CpGs with q < 0.05 and an absolute methylation difference ≥ 10%.
# ## Both the full result set and significant CpGs are saved for downstream analysis and plotting.
# 
# library(methylKit)
# 
# # Load the united methylation object (optional if resuming)
# # meth_united <- readRDS("/content/drive/MyDrive/meth_united.rds")
# 
# # Run differential methylation test using logistic regression
# diff_results <- calculateDiffMeth(meth_united)
# 
# # Save full result set (can be large)
# saveRDS(diff_results, "/content/drive/MyDrive/dmc_results.rds")
# 
# # Filter for significant DMCs: q < 0.05 and delta methylation ≥ 10%
# sig_cpgs <- getMethylDiff(diff_results, difference = 5, qvalue = 0.05)
# 
# # Save significant CpGs
# saveRDS(sig_cpgs, "/content/drive/MyDrive/sig_cpgs.rds")
# 
# # Preview number of significant sites and top results
# cat("Significant CpGs:", nrow(sig_cpgs), "\n")
# print(head(sig_cpgs, 5))
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Step 6.1 – Aggregate into 1 kb Genomic Tiles and Visualize
# ## This step bins CpG methylation data into 1,000 bp windows, compares methylation levels between groups,
# ## and visualizes tile-level differential methylation using volcano and Manhattan plots.
# 
# library(methylKit)
# library(ggplot2)
# library(ggrepel)
# library(viridis)
# 
# # 1. Create 1 kb tiles
# tiles_1kb <- tileMethylCounts(meth_united, win.size = 1000, step.size = 1000)
# 
# # 2. Run differential methylation on tiles
# tiles_diff_1kb <- calculateDiffMeth(tiles_1kb)
# 
# # 3. Save result
# saveRDS(tiles_diff_1kb, "/content/drive/MyDrive/tiles_diff_1kb.rds")
# 
# # 4. Prepare DataFrame for plotting
# tiles_df <- as.data.frame(tiles_diff_1kb)
# tiles_df$log10q <- -log10(tiles_df$qvalue)
# tiles_df$signif <- tiles_df$qvalue < 0.05 & abs(tiles_df$meth.diff) >= 10
# tiles_df$pos <- (tiles_df$start + tiles_df$end) / 2
# tiles_df$chr <- factor(tiles_df$chr, levels = unique(tiles_df$chr))
# 
# # 5. Volcano Plot
# volcano_plot <- ggplot(tiles_df, aes(x = meth.diff, y = log10q)) +
#   geom_point(aes(color = signif), alpha = 0.6, size = 1.2) +
#   scale_color_viridis(discrete = TRUE, option = "D") +
#   labs(title = "Volcano Plot – 1 kb Tiles",
#        x = "Methylation Difference (%)",
#        y = expression(-log[10](qvalue))) +
#   theme_minimal(base_size = 13) +
#   theme(legend.position = "top")
# 
# # 6. Manhattan Plot
# manhattan_plot <- ggplot(tiles_df, aes(x = pos, y = log10q, color = chr)) +
#   geom_point(size = 0.5, alpha = 0.5) +
#   facet_wrap(~ chr, scales = "free_x", nrow = 3) +
#   scale_color_viridis_d(option = "C") +
#   labs(title = "Manhattan Plot – 1 kb Tiles",
#        x = "Genomic Position",
#        y = expression(-log[10](qvalue))) +
#   theme_minimal(base_size = 12) +
#   theme(legend.position = "none")
# 
# # 7. Save plots to Drive
# ggsave("/content/drive/MyDrive/volcano_tiles1kb.png", volcano_plot, width = 8, height = 6, dpi = 300)
# ggsave("/content/drive/MyDrive/manhattan_tiles1kb.png", manhattan_plot, width = 10, height = 6, dpi = 300)
# 
# # 8. Display inline
# print(volcano_plot)
# print(manhattan_plot)
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Rebuild volcano plot with white background and improved style
# volcano_plot <- ggplot(tiles_df, aes(x = meth.diff, y = log10q)) +
#   geom_point(aes(color = signif), alpha = 0.6, size = 1.2) +
#   scale_color_manual(values = c("grey80", "firebrick")) +
#   theme_bw(base_size = 13) +
#   labs(title = "Volcano Plot – 1 kb Tiles",
#        x = "Methylation Difference (%)",
#        y = expression(-log[10](qvalue))) +
#   theme(legend.position = "top",
#         panel.grid.major = element_line(size = 0.3),
#         panel.grid.minor = element_blank())
# 
# # Rebuild manhattan plot with improved layout
# manhattan_plot <- ggplot(tiles_df, aes(x = pos, y = log10q, color = chr)) +
#   geom_point(size = 0.3, alpha = 0.4) +
#   facet_wrap(~ chr, scales = "free_x", nrow = 5) +
#   scale_color_viridis_d(option = "C") +
#   theme_bw(base_size = 11) +
#   labs(title = "Manhattan Plot – 1 kb Tiles",
#        x = "Genomic Position (bp)",
#        y = expression(-log[10](qvalue))) +
#   theme(legend.position = "none",
#         axis.text.x = element_blank(),
#         panel.grid.major = element_line(size = 0.3),
#         strip.text = element_text(size = 9),
#         plot.title = element_text(hjust = 0.5, face = "bold"))
# 
# # Overwrite updated plots to Drive
# ggsave("/content/drive/MyDrive/volcano_tiles1kb.png", volcano_plot, width = 7.5, height = 5.5, dpi = 300)
# ggsave("/content/drive/MyDrive/manhattan_tiles1kb.png", manhattan_plot, width = 11, height = 6.5, dpi = 300)
# 
# # Display again in notebook
# print(volcano_plot)
# print(manhattan_plot)
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Refined Volcano Plot – White Background
# volcano_plot <- ggplot(tiles_df, aes(x = meth.diff, y = log10q)) +
#   geom_point(aes(color = signif), alpha = 0.65, size = 1.5) +
#   scale_color_viridis(discrete = TRUE, option = "D") +
#   labs(title = "Volcano Plot – 1 kb Tiles",
#        x = "Methylation Difference (%)",
#        y = expression(-log[10](qvalue))) +
#   theme_bw(base_size = 13) +
#   theme(legend.position = "top",
#         panel.grid.major = element_line(size = 0.2, color = "gray85"),
#         panel.grid.minor = element_blank())
# 
# # Refined Manhattan Plot – Clean Layout, Larger Size
# manhattan_plot <- ggplot(tiles_df, aes(x = pos, y = log10q, color = chr)) +
#   geom_point(size = 0.6, alpha = 0.4) +
#   facet_wrap(~ chr, scales = "free_x", nrow = 4) +
#   scale_color_viridis_d(option = "B") +
#   labs(title = "Manhattan Plot – 1 kb Tiles",
#        x = "Genomic Position", y = expression(-log[10](qvalue))) +
#   theme_bw(base_size = 12) +
#   theme(legend.position = "none",
#         strip.text = element_text(size = 8),
#         axis.text.x = element_text(size = 6),
#         panel.grid.major = element_line(size = 0.2, color = "gray85"),
#         panel.grid.minor = element_blank())
# 
# # Save refined versions
# ggsave("/content/drive/MyDrive/volcano_tiles1kb_refined.png", volcano_plot, width = 7, height = 5, dpi = 300)
# ggsave("/content/drive/MyDrive/manhattan_tiles1kb_refined.png", manhattan_plot, width = 12, height = 7, dpi = 300)
# 
# # Display inline
# print(volcano_plot)
# print(manhattan_plot)
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Step 6.2 – Aggregate into 500 bp Genomic Tiles and Visualize
# ## This step bins the genome into 500 bp windows to capture more localized DMRs.
# ## We apply differential testing between groups and generate refined volcano and Manhattan plots.
# 
# # 1. Create 500 bp tiles
# tiles_500bp <- tileMethylCounts(meth_united, win.size = 500, step.size = 500)
# 
# # 2. Run differential methylation
# tiles_diff_500bp <- calculateDiffMeth(tiles_500bp)
# 
# # 3. Save RDS
# saveRDS(tiles_diff_500bp, "/content/drive/MyDrive/tiles_diff_500bp.rds")
# 
# # 4. Prepare DataFrame
# tiles_df_500 <- as.data.frame(tiles_diff_500bp)
# tiles_df_500$log10q <- -log10(tiles_df_500$qvalue)
# tiles_df_500$signif <- tiles_df_500$qvalue < 0.05 & abs(tiles_df_500$meth.diff) >= 10
# tiles_df_500$pos <- (tiles_df_500$start + tiles_df_500$end) / 2
# tiles_df_500$chr <- factor(tiles_df_500$chr, levels = unique(tiles_df_500$chr))
# 
# # 5. Volcano Plot – Refined
# volcano_500 <- ggplot(tiles_df_500, aes(x = meth.diff, y = log10q)) +
#   geom_point(aes(color = signif), alpha = 0.65, size = 1.5) +
#   scale_color_viridis(discrete = TRUE, option = "D") +
#   labs(title = "Volcano Plot – 500 bp Tiles",
#        x = "Methylation Difference (%)",
#        y = expression(-log[10](qvalue))) +
#   theme_bw(base_size = 13) +
#   theme(legend.position = "top",
#         panel.grid.major = element_line(size = 0.2, color = "gray85"),
#         panel.grid.minor = element_blank())
# 
# # 6. Manhattan Plot – Refined
# manhattan_500 <- ggplot(tiles_df_500, aes(x = pos, y = log10q, color = chr)) +
#   geom_point(size = 0.5, alpha = 0.4) +
#   facet_wrap(~ chr, scales = "free_x", nrow = 4) +
#   scale_color_viridis_d(option = "B") +
#   labs(title = "Manhattan Plot – 500 bp Tiles",
#        x = "Genomic Position", y = expression(-log[10](qvalue))) +
#   theme_bw(base_size = 12) +
#   theme(legend.position = "none",
#         strip.text = element_text(size = 8),
#         axis.text.x = element_text(size = 6),
#         panel.grid.major = element_line(size = 0.2, color = "gray85"),
#         panel.grid.minor = element_blank())
# 
# # 7. Save Plots
# ggsave("/content/drive/MyDrive/volcano_tiles500bp.png", volcano_500, width = 7, height = 5, dpi = 300)
# ggsave("/content/drive/MyDrive/manhattan_tiles500bp.png", manhattan_500, width = 12, height = 7, dpi = 300)
# 
# # 8. Display Inline
# print(volcano_500)
# print(manhattan_500)
#

# Commented out IPython magic to ensure Python compatibility.
# #Step 7.0a — Install R Packages
# %%R
# install.packages("ggplot2", repos = "https://cloud.r-project.org")
# install.packages("RColorBrewer", repos = "https://cloud.r-project.org")
# install.packages("viridis", repos = "https://cloud.r-project.org")
# install.packages("pheatmap", repos = "https://cloud.r-project.org")
# install.packages("gridExtra", repos = "https://cloud.r-project.org")
# install.packages("reshape2", repos = "https://cloud.r-project.org")
# 
# # Some packages are only available via Bioconductor
# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager", repos = "https://cloud.r-project.org")
# 
# BiocManager::install("ComplexHeatmap", update = FALSE, ask = FALSE)
# BiocManager::install("factoextra", update = FALSE, ask = FALSE)
# BiocManager::install("methylKit", update = FALSE, ask = FALSE)
#

# Commented out IPython magic to ensure Python compatibility.
# #Load Libraries
# %%R
# # Install the jpeg package (only run once)
# if (!requireNamespace("jpeg", quietly = TRUE)) {
#     install.packages("jpeg", repos = "http://cran.us.r-project.org")
# }
# 
# # Load all necessary libraries
# library(methylKit)
# library(ggplot2)
# library(ComplexHeatmap)
# library(RColorBrewer)
# library(viridis)
# library(pheatmap)
# library(gridExtra)
# library(factoextra)
# library(reshape2)
# library(jpeg)  # Required to read .jpeg images

# Commented out IPython magic to ensure Python compatibility.
# #Step 7.1 — Heatmap of Sample-Wise Correlations
# %%R
# library(methylKit)
# library(pheatmap)
# library(RColorBrewer)
# library(jpeg)
# library(grid)
# 
# # 1. Extract methylation beta values matrix
# meth_matrix <- percMethylation(meth_united)
# 
# # 2. Compute Pearson correlation matrix
# cor_matrix <- cor(meth_matrix, method = "pearson")
# 
# # 3. Define brighter color palette (diverging)
# heatmap_colors <- colorRampPalette(rev(brewer.pal(n = 11, name = "RdYlBu")))(100)
# 
# # 4. Output file path
# heatmap_file <- "/content/drive/MyDrive/step7_heatmap_correlation.jpeg"
# 
# # 5. Save high-resolution heatmap with axis labels
# jpeg(filename = heatmap_file, width = 3000, height = 2400, res = 600, quality = 100)
# pheatmap(cor_matrix,
#          color = heatmap_colors,
#          clustering_distance_rows = "euclidean",
#          clustering_distance_cols = "euclidean",
#          clustering_method = "complete",
#          show_rownames = TRUE,
#          show_colnames = TRUE,
#          fontsize = 8,
#          border_color = NA,
#          main = "Methylation Correlations")
# dev.off()
# 
# # 6. Display in Colab
# grid::grid.raster(jpeg::readJPEG(heatmap_file))

# Commented out IPython magic to ensure Python compatibility.
# #Step 7.2–PCA Plot of Methylation Profiles
# %%R
# library(factoextra)
# library(ggplot2)
# library(jpeg)
# library(grid)
# 
# # 1. Extract β-values matrix
# meth_matrix <- percMethylation(meth_united)
# 
# # 2. Remove zero-variance CpG sites
# zero_var_cols <- apply(meth_matrix, 1, function(x) var(x, na.rm = TRUE) == 0)
# meth_filtered <- meth_matrix[!zero_var_cols, ]
# 
# # 3. Transpose matrix
# meth_t <- t(meth_filtered)
# 
# # 4. PCA
# pca_res <- prcomp(meth_t, center = TRUE, scale. = TRUE)
# 
# # 5. Group assignment
# sample_ids <- getSampleID(meth_united)
# group_labels <- ifelse(grepl("GSM13274[42-65]", sample_ids), "Exposed", "Control")
# 
# # 6. PCA Plot with centered title and bright colors
# pca_plot <- fviz_pca_ind(pca_res,
#                          geom.ind = "point",
#                          col.ind = group_labels,
#                          palette = c("#FF5733", "#33C3FF"),
#                          addEllipses = TRUE,
#                          ellipse.type = "confidence",
#                          legend.title = "Group",
#                          title = "PCA of Methylation Profiles") +
#             theme(plot.title = element_text(hjust = 0.5))
# 
# # 7. Save 600 dpi JPEG
# pca_file <- "/content/drive/MyDrive/step7_pca_methylation.jpeg"
# jpeg(filename = pca_file, width = 3000, height = 2400, res = 600, quality = 100)
# print(pca_plot)
# dev.off()
# 
# # 8. Display in Colab
# grid::grid.raster(jpeg::readJPEG(pca_file))

# Commented out IPython magic to ensure Python compatibility.
# #Step 7.3 – Box Plots of Global Methylation Distribution
# %%R
# # Load required packages
# library(ggplot2)
# library(reshape2)
# library(jpeg)
# library(grid)
# 
# # 1. Extract β-values matrix from meth_united
# meth_matrix <- percMethylation(meth_united)
# 
# # 2. Reshape matrix to long format for ggplot
# meth_df <- as.data.frame(meth_matrix)
# meth_df$CpG <- rownames(meth_df)
# long_df <- melt(meth_df, id.vars = "CpG", variable.name = "Sample", value.name = "Methylation")
# 
# # 3. Create group labels
# long_df$Group <- ifelse(grepl("GSM13274[42-65]", long_df$Sample), "Exposed", "Control")
# 
# # 4. Plot: Boxplot grouped by sample, colored by group
# box_plot <- ggplot(long_df, aes(x = Sample, y = Methylation, fill = Group)) +
#   geom_boxplot(outlier.size = 0.5, lwd = 0.2, alpha = 0.8) +
#   scale_fill_manual(values = c("Control" = "#1f78b4", "Exposed" = "#e31a1c")) +
#   labs(title = "Global Methylation Distribution per Sample",
#        x = "Sample ID", y = "β-value") +
#   theme_bw(base_size = 12) +
#   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
#         plot.title = element_text(hjust = 0.5),  # Center the title
#         legend.position = "top")
# 
# # 5. Save as high-res .jpeg (600 dpi)
# box_file <- "/content/drive/MyDrive/step7_box_methylation.jpeg"
# jpeg(filename = box_file, width = 3600, height = 2400, res = 600, quality = 100)
# print(box_plot)
# dev.off()
# 
# # 6. Display inside Colab
# grid::grid.raster(jpeg::readJPEG(box_file))
#

# Commented out IPython magic to ensure Python compatibility.
# #Step 7.4 – Bar Plot of Average Methylation per Group
# %%R
# # Load required packages
# library(ggplot2)
# library(dplyr)
# library(jpeg)
# library(grid)
# 
# # 1. Extract β-values matrix
# meth_matrix <- percMethylation(meth_united)
# meth_df <- as.data.frame(meth_matrix)
# 
# # 2. Assign sample to group
# sample_ids <- colnames(meth_df)
# group_vec <- ifelse(grepl("GSM13274[42-65]", sample_ids), "Exposed", "Control")
# 
# # 3. Compute mean β-values per sample
# sample_means <- colMeans(meth_df, na.rm = TRUE)
# group_df <- data.frame(Sample = sample_ids,
#                        MeanMeth = sample_means,
#                        Group = group_vec)
# 
# # 4. Plot violin + box plot
# vioplot <- ggplot(group_df, aes(x = Group, y = MeanMeth, fill = Group)) +
#   geom_violin(trim = FALSE, scale = "width", alpha = 0.6, color = NA) +
#   geom_boxplot(width = 0.2, outlier.shape = NA, fill = "white", color = "black") +
#   scale_fill_manual(values = c("Control" = "#1f78b4", "Exposed" = "#e31a1c")) +
#   labs(title = "Distribution of Mean Methylation by Group",
#        y = "Mean β-value", x = NULL) +
#   theme_bw(base_size = 14) +
#   theme(plot.title = element_text(hjust = 0.5),  # Center title
#         legend.position = "none")
# 
# # 5. Save plot
# vioplot_file <- "/content/drive/MyDrive/step7_violin_box_avg_methylation.jpeg"
# jpeg(filename = vioplot_file, width = 3000, height = 2400, res = 600, quality = 100)
# print(vioplot)
# dev.off()
# 
# # 6. Display inline
# grid::grid.raster(jpeg::readJPEG(vioplot_file))

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Step 7.5 – Heat-map of Significant CpGs with Hierarchical Clustering
# ## We visualise CpGs that showed significant differential methylation (q < 0.05, |Δβ| ≥ 10).
# ## The β-values are row-wise z-scaled and clustered; columns are annotated by exposure group.
# 
# # ── 1.  Load libraries ──────────────────────────────────────────────────
# library(methylKit)
# library(pheatmap)
# library(RColorBrewer)
# library(jpeg)
# library(grid)
# 
# # ── 2.  Load significant CpGs (from Step 5.0) ───────────────────────────
# sig_cpgs <- readRDS("/content/drive/MyDrive/sig_cpgs.rds")
# 
# # ── 3.  Build coordinate keys for matching ──────────────────────────────
# sig_coords <- with(getData(sig_cpgs),
#                    paste0(chr, ":", start, "-", end))
# 
# meth_mat   <- percMethylation(meth_united)
# all_coords <- with(getData(meth_united),
#                    paste0(chr, ":", start, "-", end))
# 
# match_idx  <- which(all_coords %in% sig_coords)
# 
# # Guard-rail: abort gracefully if nothing to plot
# if (length(match_idx) < 5) {
#   cat("Fewer than five CpGs matched; heat-map skipped.\n")
# } else {
# 
#   # ── 4.  Prepare z-scaled matrix ───────────────────────────────────────
#   sub_mat <- meth_mat[match_idx, ]
#   z_mat   <- t(scale(t(sub_mat)))   # row-wise z-score
# 
#   # ── 5.  Column (sample) annotation ────────────────────────────────────
#   samp_ids <- colnames(z_mat)
#   grp_lbl  <- ifelse(grepl("GSM13274[42-65]", samp_ids), "Exposed", "Control")
#   ann_col  <- data.frame(Group = grp_lbl)
#   rownames(ann_col) <- samp_ids
# 
#   # ── 6.  Produce and save the heat-map (600 dpi, white bg) ─────────────
#   out_file <- "/content/drive/MyDrive/step7_heatmap_sig_cpgs.jpeg"
#   jpeg(out_file, width = 3000, height = 2400, res = 600, quality = 100)
#   ph <- pheatmap(z_mat,
#                  annotation_col          = ann_col,
#                  clustering_distance_rows = "euclidean",
#                  clustering_distance_cols = "euclidean",
#                  clustering_method        = "ward.D2",
#                  color = colorRampPalette(brewer.pal(9, "RdYlBu"))(100),
#                  show_rownames = FALSE,
#                  show_colnames = TRUE,
#                  main = "Clustered Heat-map of Significant CpGs")
#   dev.off()
# 
#   # ── 7.  Display only if file exists ───────────────────────────────────
#   if (file.exists(out_file)) {
#     grid::grid.raster(jpeg::readJPEG(out_file))
#   } else {
#     cat("Heat-map file was not created – please check write permissions.\n")
#   }
# }
#

# Commented out IPython magic to ensure Python compatibility.
# ## Step 8.1 — Compute and Export the β Matrix Using Actual CpG Coordinates
# ## Goal: Calculate the β methylation matrix from the methylKit object and export it with real CpG positions.
# ## Method: β = numCs / coverage per sample; each row corresponds to a CpG (chr:start), columns to sample IDs.
# 
# %%R
# 
# # Load necessary package
# library(methylKit)
# 
# # Load the unified methylation object saved from previous steps
# meth_united <- readRDS("/content/drive/MyDrive/meth_united.rds")
# 
# # Extract methylation data (contains numCs, coverage, and CpG coordinates)
# dt <- getData(meth_united)
# 
# # Get sample names from the methylKit object
# samples <- meth_united@sample.ids
# 
# # Calculate the β matrix (beta = numCs / coverage) for all samples
# beta_matrix <- sapply(seq_along(samples), function(i) {
#   dt[[paste0("numCs", i)]] / dt[[paste0("coverage", i)]]
# })
# colnames(beta_matrix) <- samples
# 
# # Add CpG coordinates as rownames for biological traceability
# rownames(beta_matrix) <- paste0(dt$chr, ":", dt$start)
# 
# # Convert to a data frame and include CpG coordinates as a column
# beta_df <- as.data.frame(beta_matrix)
# beta_df$CpG <- rownames(beta_matrix)
# 
# # Reorder columns: CpG first, followed by sample columns
# beta_df <- beta_df[, c("CpG", samples)]
# 
# # Save the β matrix with coordinates to Google Drive
# write.csv(beta_df, file = "/content/drive/MyDrive/beta_matrix.csv", row.names = FALSE)
# cat("β matrix successfully saved as 'beta_matrix.csv' with CpG coordinates.\n")
#

# Step 8.2 – Inspect the Updated β Matrix with CpG Coordinates

import pandas as pd

# Load the saved β matrix from Google Drive
beta_path = "/content/drive/MyDrive/beta_matrix.csv"
beta_df = pd.read_csv(beta_path)

# Display matrix dimensions
print("β Matrix Dimensions (rows x columns):", beta_df.shape)

# Check presence of coordinate column
if "CpG" in beta_df.columns:
    print("\nCoordinate Column: 'CpG' confirmed.")
else:
    print("\nWarning: 'CpG' coordinate column not found.")

# Preview first 10 sample column names
sample_cols = beta_df.columns.drop("CpG")
print("\nSample Columns (first 10):", sample_cols[:10].tolist(), "...")

# Preview top 5 rows
print("\nPreview of β Matrix:")
display(beta_df.head())

# Check for missing or problematic values
na_count = beta_df.isna().sum().sum()
inf_count = ((beta_df == float("inf")) | (beta_df == float("-inf"))).sum().sum()

# Check for constant (zero-variance) rows across all samples
numeric_data = beta_df.drop(columns=["CpG"])
zero_var_rows = (numeric_data.nunique(axis=1) == 1).sum()

print(f"\nMissing values (NA): {na_count}")
print(f"Infinite values (Inf): {inf_count}")
print(f"Constant β rows (no variance across samples): {zero_var_rows}")

from google.colab import drive
drive.mount('/content/drive')

# Step 8.3 (Python) – Violin Plot of Methylation Distributions per Sample (Cleaned)
## We map each Sample to both x and hue so seaborn uses our palette correctly,
## then save with only dpi specified (no unsupported kwargs).

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.display import Image, display
import os

# 1. Load β matrix with coordinates
beta_df = pd.read_csv("/content/drive/MyDrive/beta_matrix.csv")

# 2. Melt into long form (keep CpG column for future reference)
beta_long = beta_df.melt(id_vars=["CpG"], var_name="Sample", value_name="Beta")

# 3. Plot violin + box, using hue=Sample and disabling the legend
plt.figure(figsize=(14, 6), dpi=150)
sns.violinplot(
    x="Sample", y="Beta", hue="Sample", data=beta_long,
    inner="box", palette="Paired", dodge=False, legend=False
)
plt.xticks(rotation=90, fontsize=7)
plt.title("Distribution of Methylation Proportions per Sample", fontsize=16)
plt.xlabel("Sample ID")
plt.ylabel("β-value")
plt.tight_layout()

# 4. Save high-res JPEG (600 dpi)
out_file = "/content/drive/MyDrive/step8_violin_beta.jpeg"
plt.savefig(out_file, dpi=600)
plt.close()

# 5. Display the result
if os.path.exists(out_file):
    display(Image(out_file))
else:
    print("Violin plot file was not created.")

# Step 8.4 – Global Methylation Density by Group
# We compare the overall β-value distributions between famine-exposed and control samples
# using seaborn’s KDE plots with distinct fill/color and high-resolution output for publication.

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.display import Image, display
import os

# 1. Load β matrix (with CpG coords)
beta_df = pd.read_csv("/content/drive/MyDrive/beta_matrix.csv")

# 2. Define group labels: first 24 samples = Exposed, last 24 = Control
samples = beta_df.columns.drop("CpG")
groups = ["Famine-Exposed"]*24 + ["Control"]*24
group_map = dict(zip(samples, groups))

# 3. Melt into long form and map groups
beta_long = beta_df.melt(id_vars=["CpG"], var_name="Sample", value_name="Beta")
beta_long["Group"] = beta_long["Sample"].map(group_map)

# 4. Plot KDEs
plt.figure(figsize=(8, 6), dpi=150)
sns.kdeplot(data=beta_long, x="Beta", hue="Group",
            fill=True, alpha=0.35, linewidth=1.3,
            palette={"Famine-Exposed":"#E69F00", "Control":"#56B4E9"},
            bw_adjust=1.2)
plt.xlim(0, 1)
plt.xlabel("Methylation Level (β)", fontsize=14, weight="bold")
plt.ylabel("Density", fontsize=14, weight="bold")
plt.title("Global Methylation Density by Group", fontsize=18, weight="bold")
plt.legend(title="", fontsize=12, loc="upper right", frameon=True)
plt.tight_layout()

# 5. Save as high-resolution JPEG
out_file = "/content/drive/MyDrive/plot2_methylation_density.jpeg"
plt.savefig(out_file, dpi=600)
plt.close()

# 6. Display
if os.path.exists(out_file):
    display(Image(out_file))
else:
    print("⚠️ Density plot file was not created.")

# Commented out IPython magic to ensure Python compatibility.
# ## Step 9.0 — Inspect unified methylKit object
# ## We’ll print its class, sample IDs, treatment vector, and peek at the first rows
# ## of the underlying data (chr, start, coverage, methylation counts) to confirm everything.
# 
# %%R
# # Load the object
# meth_united <- readRDS("/content/drive/MyDrive/meth_united.rds")
# 
# # 1. Class and dimensions
# cat("Object class:", class(meth_united), "\n")
# cat("Number of CpGs × samples:", dim(meth_united), "\n\n")
# 
# # 2. Sample metadata
# cat("Sample IDs:\n"); print(meth_united@sample.ids)
# cat("Treatment vector (0=Control,1=Exposed):\n"); print(meth_united@treatment)
# 
# # 3. Peek at the raw data slot
# df <- getData(meth_united)
# cat("\nColumns in getData():", names(df), "\n")
# cat("First 6 rows of getData():\n")
# print(head(df))
# 
# # 4. Quick summary of methylation matrix
# beta_mat <- percMethylation(meth_united)
# cat("\nβ matrix dimensions:", dim(beta_mat), "\n")
# cat("Chromosomes covered:", unique(df$chr), "\n")
#

# Commented out IPython magic to ensure Python compatibility.
# ## Step 9.0 Circos Plot of Δβ Across Chromosomes
# ## Three concentric tracks:
# ##   • Inner: avg β in Control (blue) & Exposed (orange)
# ##   • Middle: Δβ heatmap (blue→white→red)
# ##   • Outer: sum –log10(q) for significant CpGs
# %%R
# library(circlize)
# library(methylKit)
# library(dplyr)
# library(jpeg)
# library(grid)
# library(graphics)
# 
# # Load and process data
# meth_united <- readRDS("/content/drive/MyDrive/meth_united.rds")
# diff_obj    <- calculateDiffMeth(meth_united)
# diff_df     <- getData(diff_obj)
# sig_df      <- diff_df %>% filter(qvalue < 0.05, abs(meth.diff) >= 10)
# 
# beta_mat <- percMethylation(meth_united)
# treat    <- meth_united@treatment
# 
# coords   <- getData(meth_united)[, c("chr", "start")]
# full_df  <- cbind(coords, as.data.frame(beta_mat))
# 
# ctrl_idx <- which(treat == 0) + 2
# exp_idx  <- which(treat == 1) + 2
# chr_list <- unique(full_df$chr)
# 
# chr_summary <- bind_rows(lapply(chr_list, function(ch) {
#   sub    <- full_df[full_df$chr == ch, ]
#   avg_c  <- mean(rowMeans(sub[, ctrl_idx], na.rm = TRUE))
#   avg_e  <- mean(rowMeans(sub[, exp_idx], na.rm = TRUE))
#   d_beta <- avg_e - avg_c
#   sum_q  <- sum(-log10(sig_df$qvalue[sig_df$chr == ch]), na.rm = TRUE)
#   tibble(chr = ch, avg_ctrl = avg_c, avg_exp = avg_e, delta = d_beta, sum_logq = sum_q)
# }))
# 
# out_file <- "/content/drive/MyDrive/step9_circos_deltabeta_legend.jpeg"
# jpeg(out_file, width=3000, height=3000, res=600, quality=100)
# 
# cyto    <- read.cytoband(species="hg19")
# chr_ord <- unique(cyto$chromosome)
# circos.clear()
# circos.par(start.degree=270, gap.degree=2)
# circos.initializeWithIdeogram(species="hg19", chromosome.index=chr_ord)
# 
# # Inner: avg β values
# circos.trackPlotRegion(track.index=1, ylim=c(0, max(chr_summary$avg_ctrl + chr_summary$avg_exp)),
#   bg.border=NA, track.height=0.20,
#   panel.fun = function(x, y) {
#     ch   <- CELL_META$sector.index
#     summ <- filter(chr_summary, chr == ch)
#     xlim <- CELL_META$xlim
#     circos.rect(xlim[1], 0, xlim[2], summ$avg_ctrl, col="#56B4E9", border=NA)
#     circos.rect(xlim[1], summ$avg_ctrl, xlim[2], summ$avg_ctrl + summ$avg_exp, col="#E69F00", border=NA)
#   }
# )
# 
# # Middle: Δβ heatmap
# max_d <- max(abs(chr_summary$delta))
# col_fun <- colorRamp2(c(-max_d, 0, max_d), c("blue", "white", "red"))
# circos.trackPlotRegion(track.index=2, ylim=c(0,1), bg.border=NA, track.height=0.10,
#   panel.fun = function(x, y) {
#     ch   <- CELL_META$sector.index
#     summ <- filter(chr_summary, chr == ch)
#     xlim <- CELL_META$xlim
#     circos.rect(xlim[1], 0, xlim[2], 1, col=col_fun(summ$delta), border=NA)
#   }
# )
# 
# # Outer: q-significance bars
# max_q <- max(chr_summary$sum_logq)
# circos.trackPlotRegion(track.index=3, ylim=c(0,1), bg.border=NA, track.height=0.05,
#   panel.fun = function(x, y) {
#     ch   <- CELL_META$sector.index
#     summ <- filter(chr_summary, chr == ch)
#     mid  <- mean(CELL_META$xlim)
#     h    <- summ$sum_logq / max_q
#     circos.rect(mid - 2e6, 0, mid + 2e6, h, col="gray40", border=NA)
#   }
# )
# 
# # Add legend (manually positioned)
# legend("center", legend=c("Avg β (Ctrl)", "Avg β (Exposed)", "Δβ Heatmap", "q-significance bar"),
#        fill=c("#56B4E9", "#E69F00", "pink", "gray40"), border=NA, bty="n", cex=1.2)
# 
# dev.off()
# circos.clear()
# 
# if (file.exists(out_file)) {
#   grid.raster(readJPEG(out_file))
# } else {
#   message("⚠️ Circos plot with legend not generated.")
# }

# Commented out IPython magic to ensure Python compatibility.
# # -- Step 9.2: Chromosome-wise Ridge + Bar Methylation Visualization --
# # • Visualizes methylation distribution and group mean differences per chromosome.
# # • Combines ridgeline plots with bar plots to capture both variability and group effects.
# 
# %%R
# library(ggplot2)
# library(ggridges)
# library(dplyr)
# library(tidyr)
# library(patchwork)
# library(readr)
# library(jpeg)
# library(grid)
# 
# # 1. Load methylation data
# meth_united <- readRDS("/content/drive/MyDrive/meth_united.rds")
# beta_mat    <- percMethylation(meth_united)
# treat       <- meth_united@treatment
# coords      <- getData(meth_united)[, c("chr", "start")]
# 
# # 2. Assemble full β dataframe
# beta_df <- cbind(coords, as.data.frame(beta_mat))
# 
# # 3. Melt into long format — detect sample columns by exclusion
# sample_cols <- setdiff(colnames(beta_df), c("chr", "start"))
# beta_long <- pivot_longer(beta_df, cols = all_of(sample_cols),
#                           names_to = "Sample", values_to = "Beta")
# 
# # 4. Add Group label from treatment vector
# beta_long$Group <- rep(ifelse(treat == 0, "Control", "Exposed"), each = nrow(coords))
# 
# # 5. Clean chromosome naming and filter to chr1–22
# beta_long$chr <- factor(beta_long$chr, levels = paste0("chr", 1:22))
# beta_long <- beta_long %>% filter(!is.na(chr))
# 
# # 6. Ridge plot: β distribution per chromosome
# ridge_plot <- ggplot(beta_long, aes(x = Beta, y = chr, fill = Group)) +
#   geom_density_ridges(alpha = 0.6, scale = 1.2, rel_min_height = 0.01, size = 0.4) +
#   scale_fill_manual(values = c("Control" = "#56B4E9", "Exposed" = "#E69F00")) +
#   theme_minimal(base_size = 14) +
#   labs(title = "β-value Distribution by Chromosome",
#        x = "Methylation Level (β)", y = "Chromosome") +
#   theme(legend.position = "top")
# 
# # 7. Bar plot: group means per chromosome
# mean_beta <- beta_long %>%
#   group_by(chr, Group) %>%
#   summarise(mean_beta = mean(Beta, na.rm = TRUE), .groups = "drop")
# 
# bar_plot <- ggplot(mean_beta, aes(x = chr, y = mean_beta, fill = Group)) +
#   geom_bar(stat = "identity", position = "dodge", width = 0.6) +
#   scale_fill_manual(values = c("Control" = "#56B4E9", "Exposed" = "#E69F00")) +
#   theme_minimal(base_size = 14) +
#   labs(title = "Mean Methylation by Group", x = "Chromosome", y = "Mean β") +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "none")
# 
# # 8. Combine and save
# combo_plot <- ridge_plot / bar_plot + plot_layout(heights = c(2, 1))
# out_file <- "/content/drive/MyDrive/step9_2_ridge_bar_combo.jpeg"
# ggsave(out_file, combo_plot, width = 14, height = 10, dpi = 600)
# 
# # 9. Display inline
# grid.raster(readJPEG(out_file))
#

# Commented out IPython magic to ensure Python compatibility.
# # -- Step 9.3: Chromosome Heatmap + Volcano Insets --
# # • Heatmap: average β values (samples × chromosomes)
# # • Insets: chromosome-level Δβ vs –log10(qvalue) volcano plots
# 
# %%R
# library(ggplot2)
# library(dplyr)
# library(tidyr)
# library(patchwork)
# library(gridExtra)
# library(jpeg)
# library(grid)
# 
# # 1. Load methylation data and compute differential stats
# meth_united <- readRDS("/content/drive/MyDrive/meth_united.rds")
# beta_mat    <- percMethylation(meth_united)
# treat       <- meth_united@treatment
# samples     <- colnames(beta_mat)
# meta_df     <- getData(meth_united)[, c("chr", "start")]
# 
# # 2. Build β matrix with coords
# beta_df <- cbind(meta_df, as.data.frame(beta_mat))
# sample_ids <- colnames(beta_df)[-(1:2)]
# 
# # 3. Long-format for summarization
# beta_long <- pivot_longer(beta_df, cols = all_of(sample_ids), names_to = "Sample", values_to = "Beta")
# beta_long$Group <- rep(ifelse(treat == 0, "Control", "Exposed"), each = nrow(meta_df))
# 
# # 4. Compute per-chromosome average β per sample
# chr_beta <- beta_long %>%
#   filter(chr %in% paste0("chr", 1:22)) %>%
#   group_by(chr, Sample) %>%
#   summarise(mean_beta = mean(Beta, na.rm = TRUE), .groups = "drop")
# 
# # 5. Build heatmap matrix
# heatmap_data <- chr_beta %>%
#   pivot_wider(names_from = chr, values_from = mean_beta)
# heatmap_mtx <- as.matrix(heatmap_data[,-1])
# rownames(heatmap_mtx) <- heatmap_data$Sample
# heat_df <- as.data.frame(as.table(heatmap_mtx))
# colnames(heat_df) <- c("Sample", "Chromosome", "Beta")
# 
# # 6. Main heatmap plot
# heatmap_plot <- ggplot(heat_df, aes(x = Chromosome, y = Sample, fill = Beta)) +
#   geom_tile() +
#   scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 50) +
#   labs(title = "Chromosome-Wise Average Methylation per Sample",
#        x = "Chromosome", y = "Sample") +
#   theme_minimal(base_size = 12) +
#   theme(axis.text.x = element_text(angle = 45, hjust = 1),
#         legend.position = "right")
# 
# # 7. Differential methylation stats
# diff_obj <- calculateDiffMeth(meth_united)
# diff_df  <- getData(diff_obj) %>%
#   filter(chr %in% paste0("chr", 1:22)) %>%
#   mutate(logq = -log10(qvalue))
# 
# # 8. Volcano plots per chromosome
# volcano_list <- lapply(unique(diff_df$chr), function(chr_name) {
#   sub <- diff_df %>% filter(chr == chr_name)
#   ggplot(sub, aes(x = meth.diff, y = logq)) +
#     geom_point(alpha = 0.3, size = 0.4) +
#     geom_vline(xintercept = c(-10, 10), linetype = "dashed", color = "gray50") +
#     geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "gray50") +
#     theme_void() +
#     ggtitle(chr_name) +
#     theme(plot.title = element_text(size = 7, hjust = 0.5))
# })
# 
# # 9. Arrange volcano plots as a grid
# volcano_grid <- wrap_plots(volcano_list, ncol = 6) +
#   plot_annotation(title = "Volcano Insets: Δβ vs –log10(q) per Chromosome")
# 
# # 10. Final combined layout
# combo_plot <- heatmap_plot / volcano_grid + plot_layout(heights = c(1.5, 1))
# 
# # 11. Save and display
# out_file <- "/content/drive/MyDrive/step9_3_heatmap_volcano.jpeg"
# ggsave(out_file, combo_plot, width = 16, height = 12, dpi = 600)
# grid.raster(readJPEG(out_file))
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # -- Pre-Step 10.0: Install Required Packages --
# # Needed for gene annotation of CpGs (genomation, GenomicRanges, TxDb)
# 
# if (!requireNamespace("BiocManager", quietly = TRUE)) {
#   install.packages("BiocManager", repos = "https://cloud.r-project.org")
# }
# 
# BiocManager::install(c("genomation", "GenomicRanges", "TxDb.Hsapiens.UCSC.hg19.knownGene"), ask = FALSE, update = FALSE)
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Step 10.1: Derive significant CpGs from meth_united and export as CSV
# 
# # Load core libraries
# library(methylKit)
# library(dplyr)
# 
# # Load methylation object
# meth_united <- readRDS("/content/drive/MyDrive/meth_united.rds")
# 
# # Compute differential methylation (two-group comparison)
# diff_obj <- calculateDiffMeth(meth_united)
# 
# # Extract full differential methylation data
# diff_df <- getData(diff_obj)
# 
# # Filter for significant CpGs (q < 0.05 and |Δβ| ≥ 10%)
# sig_df <- diff_df %>%
#   filter(qvalue < 0.05, abs(meth.diff) >= 5)
# 
# # Export to CSV
# write.csv(sig_df, "/content/drive/MyDrive/sig_cpgs.csv", row.names = FALSE)
# 
# # Preview structure
# print(glimpse(sig_df))
# cat("sig_cpgs.csv\nTotal significant CpGs:", nrow(sig_df), "\n")
#

# Commented out IPython magic to ensure Python compatibility.
# # Install missing dependencies required for annotation via UCSC RefGene (only needed once)
# %%R
# if (!requireNamespace("txdbmaker", quietly = TRUE)) {
#   BiocManager::install("txdbmaker")
# }
#

# Commented out IPython magic to ensure Python compatibility.
# # -- Step 10.2  Annotate Significant CpGs for GSEA (ChIPseeker, fixed) --
# # • Maps the 59 CpGs to promoters/exons/introns/intergenic + gene symbols
# # • Outputs annotated_sig_cpgs.csv for downstream GSEA
# 
# %%R
# # Install once if needed
# if (!requireNamespace("ChIPseeker", quietly = TRUE)) {
#   BiocManager::install(c("ChIPseeker", "org.Hs.eg.db"), ask = FALSE, update = FALSE)
# }
# 
# # Load libraries
# library(ChIPseeker)
# library(GenomicRanges)
# library(TxDb.Hsapiens.UCSC.hg19.knownGene)
# library(dplyr)
# 
# # 1. Read significant CpGs
# sig_cpgs <- read.csv("/content/drive/MyDrive/sig_cpgs.csv")
# 
# # 2. Convert to GRanges
# gr_cpgs <- GRanges(seqnames = sig_cpgs$chr,
#                    ranges   = IRanges(start = sig_cpgs$start, end = sig_cpgs$end),
#                    strand   = sig_cpgs$strand)
# 
# # 3. Annotate peaks
# txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene
# anno  <- annotatePeak(gr_cpgs,
#                       TxDb      = txdb,
#                       tssRegion = c(-2000, 2000),
#                       annoDb    = "org.Hs.eg.db")
# 
# anno_df <- as.data.frame(anno)
# 
# # 4. Merge CpG stats with annotation (use dplyr::select to avoid masking)
# annot_df <- sig_cpgs %>%
#   bind_cols(
#     dplyr::select(anno_df,
#                   geneId,
#                   SYMBOL,
#                   annotation,
#                   distanceToTSS)
#   )
# 
# # 5. Save file
# out_file <- "/content/drive/MyDrive/annotated_sig_cpgs.csv"
# write.csv(annot_df, out_file, row.names = FALSE)
# 
# # 6. Summary
# cat("saved", out_file, "with", nrow(annot_df), "CpGs\n\n")
# print(table(annot_df$annotation))
#

# Commented out IPython magic to ensure Python compatibility.
# # -- Step 11.0 : Install / Update Advanced GSEA & Plotting Tool-chain --
# # • clusterProfiler, enrichplot  – universal enrichment + void/cnetplots
# # • msigdbr                       – Hallmark & BioPlanet gene sets
# # • ggplot2 + ggraph + igraph     – radial-hive, chord, circos-arc custom plots
# # • ggnewscale + patchwork        – layered colour scales & layout
# # • ComplexHeatmap               – publication-grade heatmaps
# # • circlize                     – chord / arc / circos helper
# # • ggrepel, ggridges            – label & ridge options used earlier
# # • org.Hs.eg.db                 – symbol ↔ Entrez mapping
# # • data.table                   – fast I/O for large GMT tables
# 
# %%R
# if (!requireNamespace("BiocManager", quietly = TRUE))
#   install.packages("BiocManager", repos = "https://cloud.r-project.org")
# 
# BiocManager::install(
#   c("clusterProfiler",
#     "enrichplot",
#     "ComplexHeatmap",
#     "org.Hs.eg.db",
#     "msigdbr",
#     "circlize"),
#   ask   = FALSE,
#   update= FALSE
# )
# 
# # CRAN extras
# install.packages(
#   c("ggraph", "igraph", "ggnewscale", "patchwork", "ggrastr", "ggridges"),
#   repos = "https://cloud.r-project.org"
# )
# 
# # Load once to confirm
# library(clusterProfiler)
# library(enrichplot)
# library(ComplexHeatmap)
# library(msigdbr)
# library(circlize)
# library(ggraph)
# library(ggplot2)
# library(patchwork)
# library(org.Hs.eg.db)
#

# Commented out IPython magic to ensure Python compatibility.
# # STEP 11.1  Aging-GO UP  (enrichR CSV only)
# # • Reads gene symbols from annotated_sig_cpgs.csv
# # • Uses enrichR’s “Aging_Perturbations_from_GEO_up” library
# # • Saves raw enrichment table to Drive; no plotting yet
# 
# %%R
# # 0  Install/Load enrichR -------------------------------------------------
# if (!requireNamespace("enrichR", quietly = TRUE)) {
#   install.packages("enrichR", repos = "https://cloud.r-project.org")
# }
# library(enrichR)
# 
# # 1  Load annotated CpGs and pull SYMBOL column --------------------------
# annot_file <- "/content/drive/MyDrive/annotated_sig_cpgs.csv"
# annot_df   <- read.csv(annot_file, stringsAsFactors = FALSE)
# 
# gene_list <- unique(na.omit(annot_df$SYMBOL))
# gene_list <- gene_list[ gene_list != "" ]
# 
# cat("Gene symbols for enrichment:", length(gene_list), "\n\n")
# 
# # 2  Save gene list (reproducibility) ------------------------------------
# write.csv(gene_list,
#           "/content/drive/MyDrive/gene_list_for_enrichment.csv",
#           row.names = FALSE)
# 
# # 3  Run enrichR on Aging-UP library -------------------------------------
# dbs <- c("Aging_Perturbations_from_GEO_up")
# enrich_out <- enrichr(gene_list, dbs)
# 
# aging_up_df <- enrich_out[["Aging_Perturbations_from_GEO_up"]]
# 
# # 4  Save results to Drive ----------------------------------------------
# out_csv <- "/content/drive/MyDrive/enrichment_aging_up.csv"
# write.csv(aging_up_df, out_csv, row.names = FALSE)
# cat("Enrichment table saved:", out_csv, "\n\n")
# 
# # 5  Preview first few rows ---------------------------------------------
# print(head(aging_up_df[, c("Term", "Adjusted.P.value", "Overlap", "Combined.Score")]))
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Inspect /content/drive/MyDrive/enrichment_aging_up.csv -------------
# library(readr); library(dplyr)
# 
# csv <- "/content/drive/MyDrive/enrichment_aging_up.csv"
# enr_df <- read_csv(csv, show_col_types = FALSE)
# 
# cat("\nFile:", csv,
#     "\nRows:", nrow(enr_df), "  Columns:", ncol(enr_df), "\n\n")
# 
# print(colnames(enr_df))
# 
# cat("\nFirst 4 rows ↓\n")
# print(head(enr_df, 4))
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # STEP 11.1-B — Aging-UP radial-hive (top ≤10 terms)
# 
# library(readr);  library(dplyr);  library(stringr)
# library(tidyr);  library(igraph); library(ggraph)
# library(circlize); library(jpeg);  library(grid)
# 
# enr_df <- read_csv("/content/drive/MyDrive/enrichment_aging_up.csv",
#                    show_col_types = FALSE)
# if (nrow(enr_df) == 0L)
#   stop("🚫 enrichment_aging_up.csv is empty – nothing to plot")
# 
# top_df <- enr_df %>% arrange(Adjusted.P.value) %>%
#           slice_head(n = min(10, nrow(enr_df)))
# 
# edges <- top_df %>%
#          separate_rows(Genes, sep = ",") %>%
#          mutate(Genes = str_trim(Genes)) %>%
#          transmute(term = Term, gene = Genes)
# 
# nodes <- tibble(name = unique(c(edges$term, edges$gene)),
#                 type = ifelse(name %in% top_df$Term, "Term", "Gene"))
# 
# # colour scale (robust to identical q-values)
# log10q <- -log10(top_df$Adjusted.P.value)
# u_vals <- unique(log10q)
# if (length(u_vals) == 1) {
#   col_fun <- colorRamp2(c(u_vals - .05, u_vals + .05),
#                         c("#FFE733", "#FF1493"))
# } else {
#   col_fun <- colorRamp2(range(log10q), c("#FFE733", "#FF1493"))
# }
# term_col <- setNames(col_fun(log10q), top_df$Term)
# 
# g  <- graph_from_data_frame(edges, vertices = nodes, directed = FALSE)
# p  <- ggraph(g, layout = "hive", axis = "type") +
#       geom_edge_hive(colour = "grey80", alpha = .4, width = .4) +
#       geom_node_point(aes(colour = ifelse(type == "Term", name, "Gene"),
#                           size   = ifelse(type == "Term", 7, 3))) +
#       scale_colour_manual(values = c(term_col, Gene = "#06A7FF")) +
#       scale_size_identity() +
#       theme_void() +
#       ggtitle("Aging GEO UP – Top Enriched Terms") +
#       theme(plot.title = element_text(hjust = .5, face = "bold", size = 24))
# 
# out_img <- "/content/drive/MyDrive/step11_aging_up_radial_hive.jpeg"
# jpeg(out_img, width = 3000, height = 3000, res = 600, quality = 100)
# print(p)                       # <<< ensure the plot is sent to device
# dev.off()
# 
# if (file.exists(out_img)) {
#   grid::grid.raster(readJPEG(out_img))
# } else {
#   message("⚠️  Plot did not save – please check path and permissions")
# }
#

# Commented out IPython magic to ensure Python compatibility.
# # STEP 11.1-BAR • Aging-UP enrichment  (one-colour-per-bar)
# 
# %%R
# suppressPackageStartupMessages({
#   library(readr);  library(dplyr);  library(stringr)
#   library(ggplot2); library(RColorBrewer); library(jpeg); library(grid)
# })
# 
# # 1 ▸ load & prepare ----------------------------------------------------------
# enr <- read_csv("/content/drive/MyDrive/enrichment_aging_up.csv",
#                 show_col_types = FALSE)
# 
# top10 <- enr %>%
#   arrange(Adjusted.P.value) %>%
#   slice_head(n = 10) %>%
#   mutate(
#     Term   = vapply(strsplit(str_trim(Term), " +"),
#                     \(x) str_wrap(paste(head(x, 6), collapse = " "), 50),
#                     character(1)),
#     Term   = factor(Term, levels = rev(unique(Term))),
#     log10q = -log10(Adjusted.P.value)
#   )
# 
# # 2 ▸ discrete palette (10 bright shades) ------------------------------------
# bar_cols <- brewer.pal(10, "Set3")                  # or any 10-colour vector
# 
# # 3 ▸ plot -------------------------------------------------------------------
# p <- ggplot(top10, aes(x = log10q, y = Term, fill = Term)) +
#   geom_col(width = .7, colour = "white", linewidth = .25) +
#   geom_text(aes(label = sprintf("%.2f", log10q)),
#             hjust = -0.15, size = 3.2, fontface = "bold") +
#   scale_fill_manual(values = bar_cols, guide = "none") +
#   scale_x_continuous(expand = expansion(mult = c(0, .18))) +
#   labs(
#     x = expression(-log[10]~"(adj. p-value)"),
#     y = NULL,
#     title = "Aging-UP Enrichment"
#   ) +
#   theme_minimal(base_size = 13) +
#   theme(
#     plot.title  = element_text(size = 18, face = "bold", hjust = .5),
#     axis.text.y = element_text(face = "bold"),
#     axis.ticks.y = element_blank()
#   )
# 
# # 4 ▸ save & preview ---------------------------------------------------------
# out <- "/content/drive/MyDrive/step11_aging_up_bar.jpeg"
# ggsave(out, plot = p, width = 10, height = 7, dpi = 600)
# 
# if (file.exists(out)) {
#   grid::grid.raster(jpeg::readJPEG(out))
#   message("✅ saved: ", out)
# } else {
#   message("⚠️ file was not created – check path.")
# }
#

# ════════════════════════════════════════════════════════════════════════
# STEP 12 · BINN  —  data loading  &  device-aware tensor creation
# ────────────────────────────────────────────────────────────────────────
#  Files required in Google Drive (“My Drive”):
#    • binn_beta_input_50k.npy            (X: β-values,  n_samples × n_CpGs)
#    • binn_Y_labels_gsva.npy             (Y: pathway labels, n_samples × n_pathways)
#    • binn_cpg_gene_mask.csv             (mask M₁: n_CpGs × n_genes)
#    • binn_gene_pathway_mask.csv         (mask M₂: n_genes × n_pathways)
# ════════════════════════════════════════════════════════════════════════
import os
import numpy as np
import pandas as pd
import torch
from google.colab import drive

# ── 1  mount Google Drive ───────────────────────────────────────────────
if not os.path.isdir("/content/drive"):
    drive.mount("/content/drive")

BASE_DIR = "/content/drive/My Drive/"
X_PATH         = BASE_DIR + "binn_beta_input_50k.npy"
Y_PATH         = BASE_DIR + "binn_Y_labels_gsva.npy"
MASK_CPG_PATH  = BASE_DIR + "binn_cpg_gene_mask.csv"
MASK_GENE_PATH = BASE_DIR + "binn_gene_pathway_mask.csv"

# ── 2  helper: load a mask CSV robustly ─────────────────────────────────
def load_mask(path: str, label: str) -> np.ndarray:
    """
    Loads a 0/1 mask from CSV.
      • Drops a text first column if present.
      • Converts non-numeric entries to 0.
      • Returns float32 NumPy array.
    """
    df = pd.read_csv(path, low_memory=False)

    # If the first column is non-numeric (IDs), drop it.
    if not pd.api.types.is_numeric_dtype(df.iloc[:, 0]):
        df = df.drop(df.columns[0], axis=1)

    arr = (
        df                     # DataFrame
        .apply(pd.to_numeric, errors="coerce")
        .fillna(0)
        .values
        .astype(np.float32)
    )
    density = arr.mean()
    print(f"{label:18s} → shape {arr.shape},   density {density:.4f}")
    return arr

# ── 3  load X, Y, M₁, M₂ ────────────────────────────────────────────────
X         = np.load(X_PATH).astype(np.float32)
Y         = np.load(Y_PATH).astype(np.float32)
mask_cpg  = load_mask(MASK_CPG_PATH,  "CpG→gene mask")
mask_gene = load_mask(MASK_GENE_PATH, "gene→pathway mask")

print("\nMatrix summary")
print("  X :", X.shape, X.dtype)
print("  Y :", Y.shape, Y.dtype)

# ── 4  select the best device ───────────────────────────────────────────
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("\nDevice selected : GPU —", torch.cuda.get_device_name(0))
elif "COLAB_TPU_ADDR" in os.environ:
    import torch_xla.core.xla_model as xm
    device = xm.xla_device()
    print("\nDevice selected : TPU —", xm.xla_device_hw())
else:
    device = torch.device("cpu")
    print("\nDevice selected : CPU")

# ── 5  convert NumPy → torch on chosen device ───────────────────────────
def to_tensor(arr: np.ndarray, *, dtype=torch.float32) -> torch.Tensor:
    return torch.as_tensor(arr, dtype=dtype, device=device)

X_t         = to_tensor(X)
Y_t         = to_tensor(Y)
mask_cpg_t  = to_tensor(mask_cpg)
mask_gene_t = to_tensor(mask_gene)

print("\nTorch tensors")
print("  X  :", X_t.shape, X_t.dtype)
print("  Y  :", Y_t.shape, Y_t.dtype)
print("  M₁ :", mask_cpg_t.shape)
print("  M₂ :", mask_gene_t.shape)

# tensors X_t, Y_t, mask_cpg_t, mask_gene_t are now ready for the BINN model

!pip install pyreadr

# ════════════════════════════════════════════════════════════════════════
# STEP 12.1  ·  Load β-matrix, GSVA labels and the two BINN masks
#   • X           :  (48  × 50 000)   β-values               – binn_beta_input_50k.npy
#   • Y           :  (48  × 884)      GSVA pathway z-scores   – binn_Y_labels_gsva.npy
#   • mask_cpg    :  (50 000 × 748)   CpG → Gene mapping      – binn_cpg_gene_mask.csv
#   • mask_gene   :  (748     × 884)  Gene → Pathway mapping  – binn_gene_pathway_mask.csv
# ════════════════════════════════════════════════════════════════════════
import numpy as np
import pandas as pd

# ── file locations ──────────────────────────────────────────────────────
base_path       = "/content/drive/My Drive/"
x_path          = base_path + "binn_beta_input_50k.npy"
y_path          = base_path + "binn_Y_labels_gsva.npy"
mask_cpg_path   = base_path + "binn_cpg_gene_mask.csv"
mask_gene_path  = base_path + "binn_gene_pathway_mask.csv"

# ── load .npy matrices ───────────────────────────────────────────────────
X = np.load(x_path).astype(np.float32)          # (48, 50 000)
Y = np.load(y_path).astype(np.float32)          # (48,     884)

# ── load CSV masks – force numeric & fill blanks with 0 ──────────────────
mask_cpg  = (
    pd.read_csv(mask_cpg_path,  low_memory=False, header=None)
      .apply(pd.to_numeric, errors="coerce")
      .fillna(0)
      .values.astype(np.float32)
)                                              # (50 000, 748)

mask_gene = (
    pd.read_csv(mask_gene_path, low_memory=False, header=None)
      .apply(pd.to_numeric, errors="coerce")
      .fillna(0)
      .values.astype(np.float32)
)                                              # (748, 884)

# ── confirmation ─────────────────────────────────────────────────────────
print(f"X shape                : {X.shape}")
print(f"Y shape                : {Y.shape}")
print(f"CpG→Gene mask shape    : {mask_cpg.shape}")
print(f"Gene→Pathway mask shape: {mask_gene.shape}")

# ════════════════════════════════════════════════════════════════════════
# STEP 12.3 · Persist BINN masks as binary .npy files
#   Saving the two sparse-binary masks in NumPy’s native format
#   accelerates future reloads compared with re-parsing large CSVs.
# ════════════════════════════════════════════════════════════════════════
import numpy as np
import os

# ensure previous STEP 12.1 has populated `mask_cpg` and `mask_gene`
assert 'mask_cpg'  in globals(), "mask_cpg not found – run STEP 12.1 first."
assert 'mask_gene' in globals(), "mask_gene not found – run STEP 12.1 first."

base_path = "/content/drive/My Drive/"

# ── write .npy files ────────────────────────────────────────────────────
np.save(os.path.join(base_path, "binn_cpg_gene_mask.npy"),   mask_cpg)
np.save(os.path.join(base_path, "binn_gene_pathway_mask.npy"), mask_gene)

print("Saved:")
print("  · binn_cpg_gene_mask.npy      →", mask_cpg.shape)
print("  · binn_gene_pathway_mask.npy  →", mask_gene.shape)

# ════════════════════════════════════════════════════════════════════════
# STEP 12.4 · Reload the saved .npy mask files and verify their shapes
#   (Ensures they were written correctly in STEP 12.3.)
# ════════════════════════════════════════════════════════════════════════
import numpy as np
import os

base_path = "/content/drive/My Drive/"

# ── load the binary masks ───────────────────────────────────────────────
mask_cpg_npy   = np.load(os.path.join(base_path, "binn_cpg_gene_mask.npy"))
mask_gene_npy  = np.load(os.path.join(base_path, "binn_gene_pathway_mask.npy"))

# ── confirm expected dimensions ────────────────────────────────────────
print("Reloaded .npy Shapes:")
print("  CpG→Gene mask      :", mask_cpg_npy.shape)   # expected (50000, 748)
print("  Gene→Pathway mask  :", mask_gene_npy.shape)  # expected (748, 884)

# ════════════════════════════════════════════════════════════════════════
# STEP 12.5 · Quick data sanity-check
#   • Confirms matrix dimensions
#   • Counts any NaN / Inf values in X (β matrix) and Y (pathway labels)
# ════════════════════════════════════════════════════════════════════════
import numpy as np

# — shapes ———————————————————————————————————————————————
print("X shape:", X.shape)   # β-values   (48 × 50 000)
print("Y shape:", Y.shape)   # labels     (48 ×   884)

# — NaN / Inf counts ——————————————————————————————————————
print("NaNs in X:",  np.isnan(X).sum())
print("Infs in X:",  np.isinf(X).sum())

print("NaNs in Y:",  np.isnan(Y).sum())
print("Infs in Y:",  np.isinf(Y).sum())

# ════════════════════════════════════════════════════════════════════════
# STEP 12.6 · Filter out samples whose Y-labels contain NaNs
#   • Keeps only rows where every pathway score is finite
#   • Saves the cleaned matrices back to Drive for BINN training
# ════════════════════════════════════════════════════════════════════════
import numpy as np
import os

# ── 1 ▸ identify rows with *all-finite* pathway scores ────────────────
valid_rows = np.isfinite(Y).all(axis=1)          # True if no NaN/Inf in that row
n_removed  = (~valid_rows).sum()

print(f"Samples removed due to NaNs/Infs in Y : {n_removed}")

# ── 2 ▸ subset X and Y ────────────────────────────────────────────────
X_clean = X[valid_rows]
Y_clean = Y[valid_rows]

print("Filtered X shape:", X_clean.shape)        # e.g. (48, 50000)  →  (48, 50000)
print("Filtered Y shape:", Y_clean.shape)        # e.g. (48,   884)  →  (48,   884)

# ── 3 ▸ save cleaned arrays for downstream BINN steps ─────────────────
base_path = "/content/drive/My Drive/"
np.save(os.path.join(base_path, "binn_beta_input_50k_clean.npy"),  X_clean)
np.save(os.path.join(base_path, "binn_Y_labels_gsva_clean.npy"),   Y_clean)

print("Cleaned .npy files written to Google Drive.")

# ════════════════════════════════════════════════════════════════════════
# STEP 12.6β · Mask Dimension Correction
#   • Ensures CpG→Gene = (50000, 748), Gene→Pathway = (748, 884)
#   • Strips headers, trailing rows/cols, or spurious rows with wrong size
#   • Applies hard cast to float32 for compatibility with TensorFlow
# ════════════════════════════════════════════════════════════════════════
import numpy as np

# ── 1 ▸ Load raw .npy masks from Drive ─────────────────────────────────
base_path = "/content/drive/My Drive/"
mask_cpg_raw   = np.load(base_path + "binn_cpg_gene_mask.npy", allow_pickle=False)
mask_gene_raw  = np.load(base_path + "binn_gene_pathway_mask.npy", allow_pickle=False)

# ── 2 ▸ Force correct shapes and float32 dtype ─────────────────────────
mask_cpg_fixed = mask_cpg_raw[:50000, :748].astype('float32')    # Trim to correct shape
mask_gene_fixed = mask_gene_raw[:748, :884].astype('float32')

# ── 3 ▸ Report densities and shapes ────────────────────────────────────
print("Corrected mask shapes and sparsity:")
print(f"CpG→Gene      : {mask_cpg_fixed.shape},  density = {mask_cpg_fixed.mean():.6f}")
print(f"Gene→Pathway  : {mask_gene_fixed.shape},  density = {mask_gene_fixed.mean():.6f}")

# ── 4 ▸ Save corrected masks back (optional overwrite) ────────────────
np.save(base_path + "binn_cpg_gene_mask.npy", mask_cpg_fixed)
np.save(base_path + "binn_gene_pathway_mask.npy", mask_gene_fixed)

print("Mask dimensions corrected and saved.")

# ════════════════════════════════════════════════════════════════════════
# STEP 12.6.1 · CpG Bottlenecking (Top Variable CpGs)
#   • Reduces CpG input from 50,000 → 10,000 by variance thresholding
#   • Subsets both the methylation matrix (X_clean) and mask (CpG→Gene)
#   • Saves reduced-dimension matrices for downstream training
# ════════════════════════════════════════════════════════════════════════
import numpy as np

# ── 1 ▸ Load cleaned X and Y ────────────────────────────────────────────
base_path = "/content/drive/My Drive/"
X_clean = np.load(base_path + "binn_beta_input_50k_clean.npy")     # shape: (37, 50000)
Y_clean = np.load(base_path + "binn_Y_labels_gsva_clean.npy")      # shape: (37, 884)

# ── 2 ▸ Load corrected CpG→Gene mask ───────────────────────────────────
mask_cpg = np.load(base_path + "binn_cpg_gene_mask.npy")           # shape: (50000, 748)

# ── 3 ▸ Compute column variances and select top 10,000 CpGs ────────────
cpg_variances = np.var(X_clean, axis=0)
top_cpg_indices = np.argsort(-cpg_variances)[:1000]               # top 10,000

# ── 4 ▸ Subset X and CpG→Gene mask ─────────────────────────────────────
X_reduced = X_clean[:, top_cpg_indices]                            # (37, 10000)
mask_cpg_reduced = mask_cpg[top_cpg_indices, :]                    # (10000, 748)

# ── 5 ▸ Confirm new dimensions ─────────────────────────────────────────
print("✅ CpG bottlenecking complete")
print("Reduced X shape         :", X_reduced.shape)                # (37, 10000)
print("Reduced mask_cpg shape :", mask_cpg_reduced.shape)         # (10000, 748)

# ── 6 ▸ Save new matrices ──────────────────────────────────────────────
np.save(base_path + "binn_beta_input_10k_clean.npy", X_reduced)
np.save(base_path + "binn_cpg_gene_mask_10k.npy", mask_cpg_reduced)

# ════════════════════════════════════════════════════════════════════════
# PRELIMINARY · install / upgrade Python packages for BINN on Colab Pro
#   • TPU runtime ➜ torch-xla + compatible PyTorch
#   • otherwise  ➜ skip TPU wheels gracefully
#   • suppress pip output noise
# ════════════════════════════════════════════════════════════════════════
import os, sys, subprocess, importlib, pkg_resources

def pip_install(pkg_spec: str):
    """Install a wheel if it isn’t already present (silent)."""
    pkg_name = pkg_spec.split("==")[0] if "==" in pkg_spec else pkg_spec
    try:
        pkg_resources.get_distribution(pkg_name)
    except pkg_resources.DistributionNotFound:
        print(f"⋯ installing {pkg_spec}")
        subprocess.run([sys.executable, "-m", "pip", "install", "-q", pkg_spec],
                       check=True)

# ── core scientific stack (up-to-date) ─────────────────────────────────
pip_install("numpy>=1.24")
pip_install("pandas>=1.5")

# ── PyTorch & torch-xla for TPU runtimes ──────────────────────────────
if "COLAB_TPU_ADDR" in os.environ:                         # TPU v2-8 / v3-8
    # Colab Pro generally ships with a matching torch-xla wheel, but ensure:
    pip_install("torch==2.2.1")            # CPU wheel – torch-xla patches it
    pip_install("torch_xla[tpuvm]>=2.2")   # includes torchvision-xla, etc.
else:
    # make sure GPU builds are recent enough
    pip_install("torch>=2.2")
    pip_install("torchvision>=0.17")

# ── TensorFlow (already present, but guarantee ≥2.15) ──────────────────
pip_install("tensorflow>=2.15")

print("package check / installation finished")

# ======================================================================
# STEP 12.7  Upgraded BINN model (TPU / GPU / CPU)
#   * CpG → Gene → Pathway masked layers
#   * BatchNorm + Dropout regularisation
#   * tanh output (–1 to 1) for GSVA-style scores
#   * Works on TPU-v2/v3, GPUs, or CPU (auto detected)
#   * Now REGISTERED with @register_keras_serializable() for model saving/loading
# ======================================================================
import os
import tensorflow as tf
from tensorflow.keras import layers, Model
from keras.saving import register_keras_serializable

# ---------- 1. Select accelerator ------------------------------------
try:
    tpu_resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
    tf.config.experimental_connect_to_cluster(tpu_resolver)
    tf.tpu.experimental.initialize_tpu_system(tpu_resolver)
    strategy = tf.distribute.TPUStrategy(tpu_resolver)
    print("Using TPU:", tpu_resolver.master())
except ValueError:
    gpus = tf.config.list_logical_devices("GPU")
    if gpus:
        strategy = tf.distribute.MirroredStrategy()
        print(f"Using {len(gpus)} GPU(s)")
    else:
        strategy = tf.distribute.get_strategy()
        print("CPU fallback (no accelerator detected)")

# ---------- 2. Prepare masks -----------------------------------------
mask_cpg_f32  = mask_cpg_npy.astype("float32")   # (50000, 748)
mask_gene_f32 = mask_gene_npy.astype("float32")  # (748, 884)

IN_DIM_CPG   = mask_cpg_f32.shape[0]
OUT_DIM_GENE = mask_cpg_f32.shape[1]
OUT_DIM_PATH = mask_gene_f32.shape[1]

# ---------- 3. Define BINN Model -------------------------------------
@register_keras_serializable()
class UpgradedBINN(Model):
    def __init__(self,
                 mask_cpg_gene: tf.Tensor,
                 mask_gene_path: tf.Tensor,
                 dropout_rate: float = 0.30):
        super().__init__(name="UpgradedBINN")

        self.mask_cpg_gene  = tf.constant(mask_cpg_gene,  dtype=tf.float32)
        self.mask_gene_path = tf.constant(mask_gene_path, dtype=tf.float32)

        self.W_cpg_gene = self.add_weight(
            name="W_cpg_gene",
            shape=self.mask_cpg_gene.shape,
            initializer=tf.keras.initializers.RandomNormal(stddev=0.05),
            trainable=True)
        self.b_gene = self.add_weight(
            name="b_gene",
            shape=(OUT_DIM_GENE,),
            initializer="zeros",
            trainable=True)

        self.W_gene_path = self.add_weight(
            name="W_gene_path",
            shape=self.mask_gene_path.shape,
            initializer=tf.keras.initializers.RandomNormal(stddev=0.05),
            trainable=True)
        self.b_pathway = self.add_weight(
            name="b_pathway",
            shape=(OUT_DIM_PATH,),
            initializer="zeros",
            trainable=True)

        self.bn_gene   = layers.BatchNormalization()
        self.bn_path   = layers.BatchNormalization()
        self.drop_gene = layers.Dropout(rate=dropout_rate)
        self.drop_path = layers.Dropout(rate=dropout_rate)

    def call(self, inputs, training=False):
        gene_act = tf.matmul(inputs, self.W_cpg_gene * self.mask_cpg_gene) + self.b_gene
        gene_act = tf.nn.relu(gene_act)
        gene_act = self.bn_gene(gene_act, training=training)
        gene_act = self.drop_gene(gene_act, training=training)

        path_act = tf.matmul(gene_act, self.W_gene_path * self.mask_gene_path) + self.b_pathway
        path_act = self.bn_path(path_act, training=training)
        path_act = self.drop_path(path_act, training=training)

        return tf.nn.tanh(path_act)

# ---------- 4. Build and compile inside strategy ----------------------
with strategy.scope():
    model = UpgradedBINN(mask_cpg_f32, mask_gene_f32, dropout_rate=0.30)
    model.build(input_shape=(None, IN_DIM_CPG))
    model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
                  loss="mse",
                  metrics=["mae"])

model.summary(line_length=110)

# ════════════════════════════════════════════════════════════════════════
# STEP 12.8 · Instantiate & compile the upgraded BINN  (fixed keywords)
# ════════════════════════════════════════════════════════════════════════
import tensorflow as tf

# ensure float32 dtype for accelerators
mask_cpg_f32  = mask_cpg.astype("float32")      # (50000, 748)
mask_gene_f32 = mask_gene.astype("float32")     # (  748, 884)

with strategy.scope():                # strategy was defined in STEP 12.7
    model = UpgradedBINN(
        mask_cpg_gene = mask_cpg_f32,   # ← correct keyword
        mask_gene_path = mask_gene_f32, # ← correct keyword
        dropout_rate   = 0.30
    )

    model.compile(
        optimizer = tf.keras.optimizers.Adam(1e-3),
        loss      = "mse",
        metrics   = [tf.keras.metrics.RootMeanSquaredError(name="rmse")]
    )

print("Upgraded BINN instantiated and compiled.")
print(model.summary(line_length=110))

# ════════════════════════════════════════════════════════════════════════
# STEP 12.9 · 5-fold CV for the Upgraded BINN
#   – saves best model per fold, history CSV, prediction .npy and PNG curve
#   – computes RMSE, R² and Pearson r for each fold and for the ensemble
# ════════════════════════════════════════════════════════════════════════
import os, numpy as np, pandas as pd, tensorflow as tf, matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, r2_score
from scipy.stats import pearsonr
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

# ----------------------------------------------------------------------
# 1 ▸ load the clean data prepared in STEP 12.6
# ----------------------------------------------------------------------
BASE = "/content/drive/My Drive/"
X = np.load(BASE + "binn_beta_input_50k_clean.npy")      # (37, 50000)
Y = np.load(BASE + "binn_Y_labels_gsva_clean.npy")       # (37, 884)

mask_cpg  = np.load(BASE + "binn_cpg_gene_mask.npy").astype("float32")   # (50000, 748)
mask_gene = np.load(BASE + "binn_gene_pathway_mask.npy").astype("float32")  # (748, 884)

# ----------------------------------------------------------------------
# 2 ▸ cross-validation parameters
# ----------------------------------------------------------------------
N_SPLITS   = 5
BATCH_SIZE = 8          # fits comfortably on TPU-v2-8 / single GPU
EPOCHS     = 100
PATIENCE   = 15         # early-stop if val-loss stalls

kf = KFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

rmse_scores, r2_scores, corr_scores = [], [], []
ensemble_pred = np.zeros_like(Y, dtype=np.float32)

# ----------------------------------------------------------------------
# 3 ▸ CV loop
# ----------------------------------------------------------------------
fold = 1
for train_idx, val_idx in kf.split(X):
    print(f"\n--- Fold {fold}/{N_SPLITS} ---")

    X_tr, X_val = X[train_idx], X[val_idx]
    Y_tr, Y_val = Y[train_idx], Y[val_idx]

    # build & compile inside the accelerator strategy
    with strategy.scope():
        model = UpgradedBINN(
            mask_cpg_gene = mask_cpg,
            mask_gene_path = mask_gene,
            dropout_rate   = 0.30
        )
        model.compile(
            optimizer = tf.keras.optimizers.Adam(1e-3),
            loss      = "mse",
            metrics   = [tf.keras.metrics.RootMeanSquaredError(name="rmse")]
        )

    # file paths for this fold
    prefix          = f"{BASE}binn_fold{fold}"
    model_path      = prefix + "_model.keras"
    history_csv     = prefix + "_history.csv"
    prediction_npy  = prefix + "_val_predictions.npy"
    curve_png       = prefix + "_training_curve.png"

    # callbacks
    ckpt   = ModelCheckpoint(model_path, save_best_only=True, verbose=1)
    estop  = EarlyStopping(monitor="val_loss",
                           patience=PATIENCE,
                           restore_best_weights=True,
                           verbose=1)

    history = model.fit(
        X_tr, Y_tr,
        validation_data = (X_val, Y_val),
        batch_size      = BATCH_SIZE,
        epochs          = EPOCHS,
        callbacks       = [ckpt, estop],
        verbose         = 2
    )

    # save history
    pd.DataFrame(history.history).to_csv(history_csv, index=False)

    # predict on validation fold
    Y_pred = model.predict(X_val, batch_size=BATCH_SIZE)
    np.save(prediction_npy, Y_pred)
    ensemble_pred[val_idx] = Y_pred

    # metrics
    rmse = np.sqrt(mean_squared_error(Y_val, Y_pred))
    r2   = r2_score(Y_val, Y_pred)
    corr = pearsonr(Y_val.ravel(), Y_pred.ravel())[0]

    rmse_scores.append(rmse)
    r2_scores.append(r2)
    corr_scores.append(corr)

    # plot training curves
    plt.figure(figsize=(8, 5))
    plt.plot(history.history["loss"],     label="train loss")
    plt.plot(history.history["val_loss"], label="val loss")
    plt.plot(history.history["rmse"],     label="train RMSE")
    plt.plot(history.history["val_rmse"], label="val RMSE")
    plt.xlabel("epoch")
    plt.ylabel("metric value")
    plt.title(f"Fold {fold} training curve")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(curve_png, dpi=300)
    plt.close()

    print(f"Fold {fold} metrics  –  RMSE: {rmse:.4f}   R²: {r2:.4f}   Pearson r: {corr:.4f}")
    fold += 1

# ----------------------------------------------------------------------
# 4 ▸ ensemble evaluation
# ----------------------------------------------------------------------
ensemble_rmse = np.sqrt(mean_squared_error(Y, ensemble_pred))
ensemble_r2   = r2_score(Y, ensemble_pred)
ensemble_corr = pearsonr(Y.ravel(), ensemble_pred.ravel())[0]

print("\nCross-validation summary")
print(f"Mean RMSE     : {np.mean(rmse_scores):.4f}  ± {np.std(rmse_scores):.4f}")
print(f"Mean R²       : {np.mean(r2_scores):.4f}")
print(f"Mean Pearson r: {np.mean(corr_scores):.4f}")

print("\nEnsemble evaluation")
print(f"Ensemble RMSE : {ensemble_rmse:.4f}")
print(f"Ensemble R²   : {ensemble_r2:.4f}")
print(f"Ensemble r    : {ensemble_corr:.4f}")

np.save(f"{BASE}binn_ensemble_predictions.npy", ensemble_pred)

# ════════════════════════════════════════════════════════════════════════════
# STEP 13.1 · Load BINN Model and Data for SHAP Analysis (FOLD 5)
#   - Includes class definition of UpgradedBINN for model loading
# ════════════════════════════════════════════════════════════════════════════
import numpy as np

base = "/content/drive/My Drive/"
X = np.load(base + "binn_beta_input_50k_clean.npy")      # Should be (37, 50000)
Y = np.load(base + "binn_Y_labels_gsva_clean.npy")       # Should be (37, 884)

# Check shapes
print("X shape:", X.shape)
print("Y shape:", Y.shape)

# Check data types
print("X dtype:", X.dtype)
print("Y dtype:", Y.dtype)

# Preview contents (first sample, first 5 features)
print("X[0, :5]:", X[0, :5])
print("Y[0, :5]:", Y[0, :5])

# Check for NaNs or all-zero rows
print("Any NaNs in X?", np.isnan(X).any())
print

# ============================================================================
# STEP 13.1β · SHAP SURROGATE ANALYSIS WITH TOP-k CpG FEATURES
#   - Loads full methylation input (X) and GSVA output (Y)
#   - Computes CpG variances and selects top k (e.g., 1000 CpGs)
#   - Trains Ridge regression on one GSVA pathway
#   - Computes SHAP values using KernelExplainer
#   - Plots SHAP importances and saves SHAP matrix to disk
# ============================================================================

import numpy as np
import shap
from sklearn.linear_model import Ridge
from sklearn.feature_selection import SelectKBest, f_regression

# 1. Load methylation input and GSVA pathway labels
base = "/content/drive/My Drive/"
X = np.load(base + "binn_beta_input_50k_clean.npy")      # shape: (37, 50000)
Y = np.load(base + "binn_Y_labels_gsva_clean.npy")       # shape: (37, 884)

# 2. Choose pathway index to explain
target_index = 0
y_single = Y[:, target_index]

# 3. Select top k CpGs by variance (or f-score)
k = 1000
selector = SelectKBest(score_func=f_regression, k=k)
X_reduced = selector.fit_transform(X, y_single)

print("Original X shape:", X.shape)
print("Reduced X shape:", X_reduced.shape)

# 4. Train Ridge surrogate model
model = Ridge(alpha=1.0)
model.fit(X_reduced, y_single)

# 5. Create SHAP explainer on reduced CpG matrix
explainer = shap.KernelExplainer(model.predict, X_reduced[:10])

# 6. Compute SHAP values for 5 samples
shap_values = explainer.shap_values(X_reduced[:5])   # shape: (5, 1000)

# 7. Save SHAP values and top-k CpG indices
np.save(base + "shap_values_top1000.npy", shap_values)
np.save(base + "top1000_cpg_indices.npy", selector.get_support(indices=True))

print("✅ SHAP values and top-k CpG indices saved.")
print("SHAP matrix shape:", np.array(shap_values).shape)

# 8. Optional plot
shap.summary_plot(shap_values, X_reduced[:5])

# Commented out IPython magic to ensure Python compatibility.
# ════════════════════════════════════════════════════════════════════════
# STEP 13.2α · Extract BINN Gene Names from CpG→Gene Map (RDS → CSV)
# Input: 'binn_cpg_to_gene_map.rds'
# Output: 'binn_gene_names.csv' (for Python SHAP projection)
# Location: /content/drive/My Drive/
# ════════════════════════════════════════════════════════════════════════

# Activate R in Colab
# %load_ext rpy2.ipython

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Load RDS file again
# map_file <- "/content/drive/My Drive/binn_cpg_to_gene_map.rds"
# mapping <- readRDS(map_file)
# 
# # Inspect structure of the object
# str(mapping)
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Load again if not already done
# map_file <- "/content/drive/My Drive/binn_cpg_to_gene_map.rds"
# mapping <- readRDS(map_file)
# 
# # Extract gene names from column names of the sparse matrix
# gene_names <- colnames(mapping)
# 
# # Save to CSV (compatible with Python)
# write.csv(gene_names,
#           "/content/drive/My Drive/binn_gene_names.csv",
#           row.names = FALSE, quote = TRUE)
# 
# cat("Gene names extracted and saved as CSV.")
#

# =============================================================================
# STEP 13.2 · Project SHAP CpG Scores to Genes Using BINN Mask + Gene Labels
# -----------------------------------------------------------------------------
# This step maps SHAP values (from the top-k CpGs) to their target genes using
# the CpG→Gene binary mask. It then annotates each gene with its symbol and
# ranks them by mean absolute SHAP importance.
# =============================================================================

import numpy as np
import pandas as pd

# 1. Load SHAP values and selected CpG indices
shap_values = np.load("/content/drive/My Drive/shap_values_top1000.npy")          # shape: (5, 1000)
cpg_indices = np.load("/content/drive/My Drive/top1000_cpg_indices.npy")          # shape: (1000,)

# 2. Load the full CpG→Gene binary mask (50000 × 748)
mask_cpg_gene = np.load("/content/drive/My Drive/binn_cpg_gene_mask.npy")         # shape: (50000, 748)

# 3. Load real gene symbols (748 names)
gene_names = pd.read_csv("/content/drive/My Drive/binn_gene_names.csv", header=0).squeeze().tolist()

# 4. Confirm dimension alignment
assert len(cpg_indices) == shap_values.shape[1], "Mismatch between CpG indices and SHAP matrix"
assert mask_cpg_gene.shape[1] == len(gene_names), "Gene mask and name list must align"

# 5. Compute mean absolute SHAP value for each CpG
mean_shap_cpg = np.abs(shap_values).mean(axis=0)             # shape: (1000,)

# 6. Initialize full CpG vector of zeros (50000) and insert SHAP values
full_shap_vector = np.zeros(mask_cpg_gene.shape[0])
full_shap_vector[cpg_indices] = mean_shap_cpg                # shape: (50000,)

# 7. Project SHAP to gene layer via matrix multiplication
gene_shap = np.dot(full_shap_vector, mask_cpg_gene)          # shape: (748,)

# 8. Combine with gene symbols
shap_df = pd.DataFrame({
    "Gene": gene_names,
    "SHAP_Score": gene_shap
}).sort_values("SHAP_Score", ascending=False)

# 9. Print top 15 genes by SHAP importance
print("Top 15 Genes by SHAP Score:")
print(shap_df.head(15))

# 10. Save results to CSV and optionally as .npy
shap_df.to_csv("/content/drive/My Drive/binn_gene_shap_labeled.csv", index=False)
np.save("/content/drive/My Drive/binn_shap_gene_scores.npy", gene_shap)
print("Saved: binn_gene_shap_labeled.csv and binn_shap_gene_scores.npy")

# STEP 14.1 — Load SHAP genes and CTD gene–disease associations

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Load SHAP genes
shap_df = pd.read_csv('/content/drive/My Drive/binn_gene_shap_labeled.csv')
shap_df['Gene'] = shap_df['Gene'].str.upper().str.strip()

# Get top 100 SHAP genes with non-zero scores
top_shap_df = shap_df[shap_df['SHAP_Score'] > 0].sort_values(by='SHAP_Score', ascending=False).head(100)
top_genes = set(top_shap_df['Gene'])

# Load CTD gene–disease associations
ctd_file = '/content/drive/My Drive/ctd_data/CTD_genes_diseases.tsv.gz'
ctd_df = pd.read_csv(ctd_file, sep='\t', comment='#', compression='gzip', low_memory=False)

# Preview CTD structure
print(ctd_df.columns)
print(ctd_df.shape)
ctd_df.head(3)

# STEP 14.2 — Rename CTD columns, normalize gene symbols, and save cleaned file
# This block:
# 1. Assigns correct column names from CTD documentation
# 2. Normalizes gene symbols (uppercase, stripped)
# 3. Saves a cleaned version of CTD for downstream SHAP gene filtering

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Load raw CTD file
ctd_file = '/content/drive/My Drive/ctd_data/CTD_genes_diseases.tsv.gz'
ctd_df = pd.read_csv(ctd_file, sep='\t', comment='#', compression='gzip', low_memory=False)

# Assign official column names based on CTD documentation
ctd_df.columns = [
    'GeneSymbol',         # Column 1
    'GeneID',             # Column 2
    'DiseaseName',        # Column 3
    'DiseaseID',          # Column 4
    'DirectEvidence',     # Column 5
    'InferenceChemical',  # Column 6
    'InferenceScore',     # Column 7
    'OmimIDs',            # Column 8
    'PubMedIDs'           # Column 9
]

# Normalize gene symbols
ctd_df['GeneSymbol'] = ctd_df['GeneSymbol'].str.upper().str.strip()

# Drop rows with missing gene or disease names
ctd_df = ctd_df.dropna(subset=['GeneSymbol', 'DiseaseName'])

# Save cleaned CTD file
cleaned_ctd_path = '/content/drive/My Drive/ctd_data/CTD_cleaned_gene_disease.csv'
ctd_df.to_csv(cleaned_ctd_path, index=False)

print(f"CTD cleaned file saved: {cleaned_ctd_path}")
print(f"Total rows after cleaning: {ctd_df.shape[0]}")
ctd_df.head(5)

# STEP 14.4A — Inspect NCBI gene_info structure

ncbi_file = '/content/drive/My Drive/ctd_data/Homo_sapiens.gene_info.gz'

# Load first 5 rows to inspect column names
ncbi_df_preview = pd.read_csv(ncbi_file, sep='\t', comment='#', compression='gzip', nrows=5)

# Print actual column names
print(ncbi_df_preview.columns.tolist())
ncbi_df_preview.head()

# STEP 14.4A — Assign all columns and save full renamed NCBI gene_info table

# Define the full set of official column names from NCBI gene_info schema
column_names = [
    'tax_id', 'GeneID', 'Symbol', 'LocusTag', 'Synonyms', 'dbXrefs',
    'chromosome', 'map_location', 'description', 'type_of_gene',
    'Symbol_from_nomenclature_authority', 'Full_name_from_nomenclature_authority',
    'Nomenclature_status', 'Other_designations', 'Modification_date', 'Feature_type'
]

# Load file with all columns and assign names
ncbi_file = '/content/drive/My Drive/ctd_data/Homo_sapiens.gene_info.gz'
ncbi_df = pd.read_csv(ncbi_file, sep='\t', header=None, names=column_names, comment='#', compression='gzip')

# Save full table with all columns (for rollback or exploration)
full_output_path = '/content/drive/My Drive/ctd_data/Homo_sapiens_gene_info_full.csv'
ncbi_df.to_csv(full_output_path, index=False)

# Confirm save
print(f"✅ Full NCBI gene_info saved to: {full_output_path}")
print(f"Total rows: {ncbi_df.shape[0]}")
ncbi_df.head(3)

# STEP 14.4B — Extract and save GeneID → Symbol mapping from NCBI gene_info

import pandas as pd

# Load the full file previously saved
ncbi_full_path = '/content/drive/My Drive/ctd_data/Homo_sapiens_gene_info_full.csv'
ncbi_df = pd.read_csv(ncbi_full_path)

# Extract only GeneID and Symbol, drop any rows with missing values
ncbi_map = ncbi_df[['GeneID', 'Symbol']].dropna()

# Save as mapping file
mapping_output_path = '/content/drive/My Drive/ctd_data/GeneID_to_Symbol_map.csv'
ncbi_map.to_csv(mapping_output_path, index=False)

# Confirm save and preview structure
print(f"✅ Mapping file saved to: {mapping_output_path}")
print(f"Mapping entries: {ncbi_map.shape[0]}")
ncbi_map.head(5)

# STEP 14.4C — Merge CTD cleaned file with official HGNC gene symbols (via GeneID)

# Load CTD cleaned file (has GeneID and GeneSymbol columns)
ctd_path = '/content/drive/My Drive/ctd_data/CTD_cleaned_gene_disease.csv'
ctd_df = pd.read_csv(ctd_path)

# Load GeneID → Symbol map
map_path = '/content/drive/My Drive/ctd_data/GeneID_to_Symbol_map.csv'
ncbi_map = pd.read_csv(map_path)

# Merge CTD and HGNC symbol mapping on GeneID
ctd_merged = pd.merge(ctd_df, ncbi_map, how='inner', on='GeneID')

# Rename Symbol to HGNC_Symbol to avoid confusion with CTD's original GeneSymbol
ctd_merged = ctd_merged.rename(columns={'Symbol': 'HGNC_Symbol'})

# Drop duplicates to ensure clean associations
ctd_merged = ctd_merged.drop_duplicates(subset=['HGNC_Symbol', 'DiseaseName', 'DiseaseID'])

# Save final mapped file
merged_output_path = '/content/drive/My Drive/ctd_data/CTD_gene_disease_with_HGNC.csv'
ctd_merged.to_csv(merged_output_path, index=False)

# Preview results
print(f"Merged CTD file saved to: {merged_output_path}")
print(f"Total merged rows: {ctd_merged.shape[0]}")
ctd_merged[['HGNC_Symbol', 'DiseaseName', 'InferenceScore']].head(5)

# STEP — Download large file to local desktop

from google.colab import files

# Point to the file you want to download
files.download('/content/drive/My Drive/ctd_data/CTD_cleaned_gene_disease.csv')

files.download('/content/drive/MyDrive/ctd_data/CTD_gene_disease_with_HGNC.csv')

# STEP 14.5: Filter CTD–HGNC data using full SHAP gene list (no SHAP score threshold)

import pandas as pd

# Load CTD-HGNC merged file
ctd_mapped = pd.read_csv('/content/drive/My Drive/ctd_data/CTD_gene_disease_with_HGNC.csv')

# Load full SHAP gene list
shap_df = pd.read_csv('/content/drive/My Drive/binn_gene_shap_labeled.csv')
shap_df['Gene'] = shap_df['Gene'].str.upper().str.strip()

# Use all SHAP genes (no filtering)
shap_genes = set(shap_df['Gene'])

# Filter CTD for SHAP gene matches
filtered_ctd = ctd_mapped[ctd_mapped['HGNC_Symbol'].isin(shap_genes)].copy()

# Merge CTD with SHAP scores
merged_df = pd.merge(filtered_ctd, shap_df, left_on='HGNC_Symbol', right_on='Gene', how='left')

# Select and rename relevant columns
merged_df = merged_df[['HGNC_Symbol', 'DiseaseName', 'DiseaseID', 'InferenceScore', 'SHAP_Score']]
merged_df = merged_df.rename(columns={
    'HGNC_Symbol': 'Gene',
    'InferenceScore': 'CTD_Score'
})

# Sort by SHAP score for interpretability
merged_df = merged_df.sort_values(by='SHAP_Score', ascending=False)

# Save final output
output_path = '/content/drive/My Drive/shap_gene_disease_full_matches.csv'
merged_df.to_csv(output_path, index=False)

# Preview results
print(f"Full SHAP–disease association table saved: {output_path}")
print(f"Total matched associations: {merged_df.shape[0]}")
merged_df.head(10)

# STEP — Download large file to local desktop

from google.colab import files

# Point to the file you want to download
files.download('/content/drive/MyDrive/shap_gene_disease_full_matches.csv')

# STEP 14.6a — Filter SHAP × CTD matches for chronic diseases, save as CSV

import pandas as pd

# Load SHAP–CTD match table
df = pd.read_csv('/content/drive/My Drive/shap_gene_disease_full_matches.csv')

# Chronic/inflammaging-related disease terms (expanded with 'cancer')
chronic_terms = [
    'diabetes', 'cardio', 'hypertension', 'alzheimer', 'autoimmune',
    'inflammation', 'arthritis', 'obesity', 'asthma', 'copd',
    'atherosclerosis', 'neurodegeneration', 'cancer', 'tumor', 'malignancy'
]

# Filter rows where disease name matches any chronic term
pattern = '|'.join(chronic_terms)
chronic_df = df[df['DiseaseName'].str.contains(pattern, case=False, na=False)]

# Save to CSV
output_csv = '/content/drive/My Drive/chronic_disease_shap_ctd_filtered.csv'
chronic_df.to_csv(output_csv, index=False)

print(f"Saved filtered chronic disease table: {output_csv}")
print(f"Total rows: {chronic_df.shape[0]}")
chronic_df[['Gene', 'DiseaseName', 'CTD_Score']].head(5)

# STEP 14.6b — Bar plot with color customization, saved to Drive as 600 DPI JPEG

import matplotlib.pyplot as plt
import seaborn as sns

# Aggregate CTD scores per disease
agg = chronic_df.groupby('DiseaseName')['CTD_Score'].sum().reset_index()
agg = agg.sort_values(by='CTD_Score', ascending=False).head(20)

# Create color palette
colors = sns.color_palette('cubehelix', len(agg))

# Plot
plt.figure(figsize=(12, 7))
bars = plt.barh(agg['DiseaseName'], agg['CTD_Score'], color=colors)

# Annotate bars
for bar in bars:
    plt.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
             f'{bar.get_width():.1f}', va='center', fontsize=8)

plt.xlabel('Total CTD Inference Score', fontsize=12)
plt.ylabel('Chronic Disease', fontsize=12)
plt.title('Top Chronic Diseases Associated with SHAP Genes', fontsize=14)
plt.gca().invert_yaxis()
plt.tight_layout()

# Save plot
output_fig = '/content/drive/My Drive/Figure_28a_chronic_disease_burden.jpeg'
plt.savefig(output_fig, dpi=600, format='jpeg')
print(f"✅ Figure saved: {output_fig}")

# Show plot inline
plt.show()

# STEP 14.6C Classify disease names into biological categories

import pandas as pd

# Load previously filtered chronic disease file
df = pd.read_csv('/content/drive/My Drive/chronic_disease_shap_ctd_filtered.csv')

# Define keyword-based category mapping
category_map = {
    'inflammation': 'Inflammation / Immune',
    'autoimmune': 'Inflammation / Immune',
    'arthritis': 'Inflammation / Immune',
    'rheumat': 'Inflammation / Immune',
    'cardio': 'Cardiovascular',
    'atherosclerosis': 'Cardiovascular',
    'hypertension': 'Cardiovascular',
    'heart': 'Cardiovascular',
    'obesity': 'Metabolic / Endocrine',
    'diabetes': 'Metabolic / Endocrine',
    'alzheimer': 'Neurodegenerative',
    'neurodegeneration': 'Neurodegenerative',
    'asthma': 'Pulmonary',
    'copd': 'Pulmonary',
    'lung': 'Pulmonary',
    'cancer': 'Cancer / Neoplastic',
    'tumor': 'Cancer / Neoplastic',
    'malignan': 'Cancer / Neoplastic'
}

# Assign category to each disease
def assign_category(name):
    name = str(name).lower()
    for key, category in category_map.items():
        if key in name:
            return category
    return 'Other / Systemic'

df['Category'] = df['DiseaseName'].apply(assign_category)

# Save categorized file
output_cat = '/content/drive/My Drive/chronic_disease_by_category.csv'
df.to_csv(output_cat, index=False)

# Summary
category_counts = df['Category'].value_counts().reset_index()
category_counts.columns = ['Disease Category', 'Count']

print(f"Saved categorized disease file: {output_cat}")
category_counts

# STEP 14.6d Pie chart of disease categories (bright colors, saved and displayed)

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Load categorized file
df = pd.read_csv('/content/drive/My Drive/chronic_disease_by_category.csv')

# Count occurrences per category
category_counts = df['Category'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']

# Prepare color palette (bright, qualitative)
colors = sns.color_palette('Set3', n_colors=len(category_counts))

# Plot
plt.figure(figsize=(8, 8))
plt.pie(
    category_counts['Count'],
    labels=category_counts['Category'],
    autopct='%1.1f%%',
    startangle=140,
    colors=colors,
    wedgeprops={'edgecolor': 'black', 'linewidth': 1}
)
plt.title('Distribution of SHAP-Linked Chronic Disease Categories', fontsize=14)
plt.tight_layout()

# Save at 600 DPI
output_fig = '/content/drive/My Drive/Figure_28b_disease_category_pie.jpeg'
plt.savefig(output_fig, dpi=600, format='jpeg')

print(f"Saved pie chart: {output_fig}")

# Show inline
plt.show()